/* ══════════════════════════════════════════════════════════════════════════
   HELIESCALA — todo el contenido de la página, en un solo archivo.

   Salió del HTML el 2026-09-19, al hacer el catálogo en PDF: dossier.html lee
   este mismo archivo, así que un pie de foto o un precio se cambian AQUÍ y se
   actualizan la web y el PDF a la vez (regla 1 del proyecto: un dato, un sitio).

   PERFIL es lo que se rellena; T son los textos en los dos idiomas; PERFIL_EN
   sobrescribe los tres valores de PERFIL que son texto.
   ══════════════════════════════════════════════════════════════════════════ */
/* `var`, no `const`: Posts/posts.html carga este archivo y el de Aeroresinas en la misma
   página, y dos `const PERFIL` en scripts distintos chocan. Con `var` cada uno se guarda en
   su cajón (AERO, HELI) antes de que el siguiente lo pise. Para la web es indistinto. */
var PERFIL = {
  ciudad:  'Ciudad de México',
  escalas: '[1:XX]',                      // único dato que sigue pendiente
  tiempo:  '2 semanas',
  envio:   'En persona o por DHL',
  desde:   '$1,800 MXN',
  // Solo dígitos para wa.me (52 = México); `whatsappTxt` es cómo se escribe en pantalla.
  whatsapp:    '525586184919',
  whatsappTxt: '+52 55 8618 4919',
  correo:      'adanarturomartinez@gmail.com',
  // Tarifa de DHL por zona. Se cotiza sobre la caja ya embalada, así que hasta
  // que no haya una cifra real la tabla lo dice en vez de inventarla.
  envZ2: '[$XXX]',
  envZ3: '[$XXX]',
  envZ4: '[$XXX]',
};

/* Lo que cambia de idioma. PERFIL es un solo objeto —un dato, un sitio— pero tres
   de sus valores son texto, y en inglés no pueden salir en español. Solo se
   sobrescriben esos. */
var PERFIL_EN = {
  ciudad: 'Mexico City',
  tiempo: '2 weeks',
  envio:  'In person or by DHL',
};

var T = {
 es:{
  marcaSub:'HECHO A MANO EN MÉXICO',
  navCat:'Catálogo', navTuya:'Tu aeronave', navProc:'Cómo se hace', navEnv:'Envíos', navGal:'Galería',
  visorAyuda:'CLIC EN LA FOTO PARA VERLA A TAMAÑO REAL · ← → PARA PASAR',
  kWa:'WHATSAPP', kMail:'CORREO',
  otroIdioma:'English',
  fichasNota:'Los <b>{desde}</b> son el punto de partida, no la tarifa: el precio final depende del modelo, del tamaño y de cuánta decoración lleve — no cuesta lo mismo un fuselaje gris que una librea con escudo, número de unidad y matrícula. Cada encargo se cotiza antes de empezar.',

  /* ── Entrega y envíos ───────────────────────────────────────────────────
     Los 32 estados repartidos en cuatro zonas. La primera no es una zona de
     envío: es donde la entrega él en persona, y por eso va aparte y en cian. */
  envT:'A dónde llega', envN:'ENTREGA Y ENVÍOS',
  envSub:'En la <b>Ciudad de México y el Estado de México</b> te la entrega él en persona, sin costo. Al resto del país va por <b>DHL</b>, con el envío aparte: sale embalada en caja rígida y con su número de guía.',
  envZonas:[
   ['01','Entrega en persona','Ciudad de México · Estado de México','Sin costo'],
   ['02','Centro','Hidalgo · Morelos · Puebla · Tlaxcala · Querétaro · Guanajuato · San Luis Potosí · Michoacán','@envZ2'],
   ['03','Occidente y norte','Jalisco · Colima · Nayarit · Aguascalientes · Zacatecas · Durango · Sinaloa · Coahuila · Nuevo León · Tamaulipas · Chihuahua · Sonora','@envZ3'],
   ['04','Sur, sureste y penínsulas','Guerrero · Oaxaca · Veracruz · Chiapas · Tabasco · Campeche · Yucatán · Quintana Roo · Baja California · Baja California Sur','@envZ4'],
  ],
  envNota:'El envío se cobra aparte y lo cotiza DHL sobre la caja ya embalada: una réplica pesa poco pero ocupa, y en paquetería manda el volumen, no el peso. Si encargas varias piezas, viajan en una sola caja y el envío se reparte entre todas.',

  galT:'Más piezas', galN:'GALERÍA',
  galSub:'El taller y lo que sale de él: la mesa de producción, las piezas en bruto, los lotes completos y una sala de exposición donde hay piezas suyas montadas.',
  galeria:[
   ['fotos/museo.jpg','<b>En exhibición.</b> Piezas suyas montadas sobre pedestal en una sala de exposición, detrás del cordón.'],
   ['fotos/produccion.jpg','<b>La mesa de producción.</b> Fuselajes en imprimación esperando lijado, montaje y pintura. Así empieza cada encargo.'],
   ['fotos/fila.jpg','<b>Un lote completo.</b> Modelos distintos avanzando a la vez, cada uno en su etapa.'],
   ['fotos/flota6.jpg','<b>Seis iguales.</b> Un pedido de flota: mismo modelo, mismo camuflaje, misma pintura, uno por uno.'],
   ['fotos/bruto-1.jpg','<b>Recién salido del molde.</b> La pieza en bruto, sin lijar y sin pintar, sobre la mesa de trabajo.'],
   ['fotos/bruto-2.jpg','<b>Ajuste a mano.</b> Fuselaje y cola por separado, con la lija y el pegamento al lado. Todo se prueba antes de unirlo.'],
   ['fotos/trio.jpg','<b>Tres piezas juntas.</b> Rescate, ambulancia aérea y transporte, del mismo lote.'],
   ['fotos/flota.jpg','<b>Producción en curso.</b> Fuselajes en fila, esperando montaje y pintura.'],
   ['fotos/policia.jpg','<b>Bell 412 de la policía.</b> Con su número de unidad pintado a mano.'],
  ],
  heroOjo:'Réplicas en resina · por encargo',
  heroT1:'Casi cualquier helicóptero,', heroT2:'a escala y hecho a mano.',
  heroSub:'Airbus, Bell, Mi-17, Super Puma… fundidos en resina, montados y pintados a mano. Cada modelo sale de su propio molde, y la librea, el número de unidad y la matrícula se pintan una por una.',
  ctaPedir:'Encargar una réplica', ctaVer:'Ver el catálogo',
  dModelos:'26', kModelos:'En el catálogo', dResina:'Resina', kResina:'Material', kEscala:'Escalas', kBase:'TALLER',
  pieHero:'Tres piezas terminadas: ambulancia aérea, rescate y Super Puma.',
  catT:'Algunos de los que ya ha hecho', catN:'CATÁLOGO',
  catSub:'Veintiséis piezas reales suyas, con la librea que llevaba cada original: Airbus, Bell, Agusta, Mil y hasta un avión. Civiles, de rescate, de la Marina, de la Fuerza Aérea, de la Policía y el presidencial de Estados Unidos. Si el tuyo no está, se hace: el molde y la decoración se preparan para cada encargo.',
  piezas:[
   ['h145','Airbus H145','fotos/h145.jpg','Fenestron, tren de patines y librea corporativa blanca y negra.',['AIRBUS','TWIN'],'h145'],
   ['h145a','Airbus H145 · exhibición','fotos/h145-airbus.jpg','Versión de exhibición en azul Airbus, montada sobre pedestal.',['AIRBUS','EXHIBICIÓN'],'h145'],
   ['sgm','AS350 / H125 · ambulancia','fotos/sgm.jpg','Rojo de servicios médicos, con camilla y estribos. De los más pedidos.',['AIRBUS','AEROMÉDICA'],'h125'],
   ['mi17','Mi-17','fotos/mi17.jpg','El ruso de transporte, en gris. Rotor de cinco palas y tren fijo.',['MIL','TRANSPORTE'],'mi17'],
   ['marina','Panther · Marina','fotos/marina.jpg','Tres piezas de la misma serie, en librea naval mexicana.',['MARINA','SERIE'],'panther'],
   ['rescate','Rescate · librea AESSA','fotos/rescate.jpg','Par en rojo y amarillo con flotadores de emergencia y patines altos.',['RESCATE','PAR'],''],
   ['bell407','Gobierno de SLP · XC-PSI','fotos/bell407.jpg','Dos unidades en azul y gris, con matrícula y escudo pintados a mano.',['GOBIERNO','PAR'],''],
   ['policiapar','Bell 412 · Policía','fotos/policia-par.jpg','La flota de la policía, en azul y blanco, lista para entregar.',['POLICÍA','FLOTA'],'bell412'],
   ['marineone','Presidencial de EE. UU. · verde y blanco','fotos/marineone.jpg','La librea más reconocible del mundo: verde oscuro, panza blanca y «UNITED STATES OF AMERICA» en el costado.',['EE. UU.','PRESIDENCIAL'],''],
   ['xamvr','Airbus H145 · XA-MVR','fotos/xamvr.jpg','Bimotor corporativo azul sobre blanco, con su matrícula mexicana y la bandera pintadas a mano.',['AIRBUS','MATRÍCULA'],'h145'],
   ['grandnew','AgustaWestland Grand New · XB-HFY','fotos/grandnew.jpg','Acabado plata metálico con el nombre del modelo rotulado en el morro.',['AGUSTA','EJECUTIVO'],''],
   ['aessa-mcm','Rescate AESSA · XA-MCM','fotos/aessa-mcm.jpg','Rojo y amarillo con las flechas de la librea de rescate y la matrícula bajo la cabina.',['RESCATE','MATRÍCULA'],''],
   ['aessa-jgh','Rescate AESSA · XA-JGH','fotos/aessa-jgh.jpg','La segunda unidad de la misma flota, con su propia matrícula. Se hacen iguales y se distinguen por el número.',['RESCATE','FLOTA'],''],
   ['fam-uma','Fuerza Aérea Mexicana · MX-UMA','fotos/fam-uma.jpg','Blanco con la franja verde y roja, el escudo y la matrícula. De las piezas con más rotulación a mano.',['FAM','MATRÍCULA'],'bell412'],
   ['fam-412','Bell 412 · FAM, camuflaje','fotos/fam-412.jpg','Camuflaje de manchas gris y blanco, con «FUERZA AÉREA MEXICANA» en el techo de cabina.',['FAM','CAMUFLAJE'],'bell412'],
   ['fam-sp','Super Puma · FAM 1006','fotos/fam-sp.jpg','Gris claro con su número de unidad, tren retráctil y rotor de cuatro palas.',['FAM','TRANSPORTE'],''],
   ['fam-mi17','Mi-17 · Fuerza Aérea Mexicana','fotos/fam-mi17.jpg','El transporte ruso en gris, con rotor de cinco palas, tren fijo y las marcas de la FAM.',['FAM','TRANSPORTE'],'mi17'],
   ['camo-verde','Super Puma · camuflaje verde','fotos/camo-verde.jpg','Camuflaje militar verde y café, con número de serie y escudo en la cabina.',['MILITAR','CAMUFLAJE'],''],
   ['camo-gris','Cougar · camuflaje gris','fotos/camo-gris.jpg','Manchas grises y blancas sobre todo el fuselaje, con sus depósitos laterales.',['MILITAR','CAMUFLAJE'],''],
   ['marina-cruz','Panther · Marina, sanitario','fotos/marina-cruz.jpg','Gris naval con «MARINA» y la cruz roja del servicio sanitario, y fenestrón en la cola.',['MARINA','SANITARIO'],'panther'],
   ['fenestron','Bimotor con fenestrón · azul y blanco','fotos/fenestron.jpg','Deriva azul con el rotor de cola metido dentro, y la panza blanca. Librea corporativa.',['FENESTRÓN','CORPORATIVO'],''],
   ['xaecj','Corporativo · XA-ECJ','fotos/xaecj.jpg','Blanco con grecas verdes y amarillas, con la bandera y la matrícula del operador.',['CIVIL','MATRÍCULA'],''],
   ['policia-2','Policía · Cóndores 01','fotos/policia-2.jpg','Dos unidades azules de la misma flota, con el número de unidad y el escudo.',['POLICÍA','PAR'],'bell412'],
   ['as350-grande','Monomotor rojo · pieza grande','fotos/as350-grande.jpg','Una de las piezas de mayor tamaño que ha hecho, con patines, estribos y puertas marcadas.',['GRAN FORMATO','CIVIL'],'h125'],
   ['bell-camo','Ligero militar · camuflaje','fotos/bell-camo.jpg','Rotor de dos palas con barra estabilizadora, patines altos y palas de cola en rojo y blanco.',['MILITAR','LIGERO'],''],
   ['avion','Bimotor de ala fija','fotos/avion.jpg','No todo son helicópteros: también hace aviones. Bimotor turbohélice de transporte, en verde militar.',['ALA FIJA','TRANSPORTE'],''],
  ],
  fichas:[['regla','ESCALAS','escalas'],['reloj','TIEMPO','tiempo'],['caja','ENVÍO','envio'],['etiqueta','DESDE','desde']],
  verFicha:'Ver la ficha',
  fpRepT:'La réplica', fpCta:'Encargar esta', fpDe:'de', fpRepD:'Se hace por encargo, con la librea que pidas: la de la foto, la de tu operador o la tuya propia.',
  fpSpec:{motor:'Motor', rotor:'Rotor', peso:'Peso máximo', cap:'Capacidad', vel:'Crucero', alc:'Alcance'},
  fpBl:{usos:'Para qué se usa', ojo:'Cómo se reconoce', mx:'En México'},
  fpPend:'Modelo exacto por confirmar con el taller.',
  /* ── Los helicópteros de verdad ──────────────────────────────────────────
     Cifras del fabricante, comprobadas el 2026-09-17 en airbus.com y bellflight.com
     (el Mi-17 no tiene ficha pública de fabricante: sus datos son los del Mi-8MTV,
     la versión de exportación más común). Varían con la versión y la configuración:
     si alguien necesita el número exacto de SU aeronave, va al manual, no a esta página. */
  modelos:{
   h145:{fab:'Airbus Helicopters', n:'H145 (BK117 D-3)',
     r:'El bimotor ligero más vendido de Airbus para emergencias. Cabina cuadrada con puertas traseras de concha, fenestron en la cola y, desde 2020, rotor de cinco palas sin cabeza articulada: 150 kg más de carga útil y mucho menos ruido.',
     sp:{motor:'2 × Safran Arriel 2E', rotor:'5 palas · fenestron', cap:'Hasta 10 pasajeros', vel:'241 km/h', alc:'≈ 650 km'},
     usos:'Ambulancia aérea, policía, búsqueda y rescate, transporte ejecutivo y offshore. Es el que ves cuando aterriza un helicóptero medicalizado en una carretera.',
     ojo:'El <b>fenestron</b> —el rotor de cola metido dentro de la deriva— y las <b>cinco palas</b> del rotor principal. Si tiene cuatro palas y fenestron, es el H145 anterior a 2020.',
     mx:'Vuela en servicios aeromédicos privados y en dependencias de gobierno; la versión de exhibición de Airbus es una de las piezas que más se pide.'},
   h125:{fab:'Airbus Helicopters', n:'H125 / AS350 Écureuil',
     r:'El monomotor de trabajo por excelencia. Ligero, sencillo de mantener y con una relación potencia-peso que lo hace imbatible en altura: en 2005 un AS350 B3 aterrizó y despegó en la cima del Everest, a 8,848 m — el récord sigue en pie.',
     sp:{motor:'1 × Safran Arriel 2D (952 shp)', rotor:'3 palas', peso:'2,250 kg', cap:'1 piloto + 6', vel:'252 km/h', alc:'≈ 630 km'},
     usos:'Trabajo aéreo, tendido eléctrico, combate de incendios, ambulancia aérea, turismo y vigilancia. Donde hay montaña, hay Écureuil.',
     ojo:'La silueta estrecha, el <b>rotor de tres palas</b> y el escape del motor saliendo alto, detrás del rotor. Los de ambulancia llevan camilla y estribo lateral.',
     mx:'Es de los más comunes del país: servicios médicos, gobiernos estatales, empresas de trabajo aéreo y turismo.'},
   mi17:{fab:'Mil (Rusia)', n:'Mi-17 / Mi-8MTV',
     r:'El camión del aire. Transporte medio-pesado, de mecánica robusta y pensado para operar donde no hay hangar ni pista. Es, con su antecesor el Mi-8, el helicóptero más producido de la historia.',
     sp:{motor:'2 × Klimov TV3-117 (≈2,070 shp)', rotor:'5 palas · rotor de cola de 3', peso:'13,000 kg', cap:'Hasta 24 pasajeros', vel:'225 km/h', alc:'≈ 580 km'},
     usos:'Transporte de tropa y carga, combate de incendios con helibalde, evacuación y apoyo en desastres.',
     ojo:'El <b>tamaño</b>, las puertas de concha en la cola, las ventanillas redondas y el tren de aterrizaje fijo de tres patas. No se parece a nada occidental.',
     mx:'La Fuerza Aérea Mexicana opera Mi-17 desde los años noventa, y son los que se ven en inundaciones y huracanes.'},
   panther:{fab:'Airbus Helicopters', n:'AS565 MBe Panther',
     r:'La versión naval del Dauphin: bimotor, plegable para caber en el hangar de un buque y preparado para operar sobre el mar. Es el helicóptero embarcado de la Marina.',
     sp:{motor:'2 × Safran Arriel 2N', rotor:'4 palas · fenestron', peso:'4,500 kg', vel:'≈ 305 km/h', alc:'≈ 780 km'},
     usos:'Guerra antisubmarina y antisuperficie, vigilancia marítima, interdicción, búsqueda y rescate en el mar.',
     ojo:'El <b>fenestron</b> y la deriva alta con plano de cola en T, más el tren retráctil y la sonda. La cola y las palas se pliegan.',
     mx:'La <b>Marina mexicana</b> recibió diez AS565 MBe entre 2016 y 2017, y operan desde sus buques.'},
   bell412:{fab:'Bell', n:'Bell 412',
     r:'Bimotor medio derivado del mítico Huey, con rotor de cuatro palas. La combinación de cabina grande, dos motores y mecánica conocida lo hizo el estándar de la policía y la protección civil.',
     sp:{motor:'2 × Pratt &amp; Whitney (Twin-Pac)', rotor:'4 palas', peso:'5,534 kg', cap:'1 piloto + 14', vel:'228 km/h', alc:'≈ 669 km'},
     usos:'Patrulla policial, rescate, traslado de personal, combate de incendios y transporte a plataformas.',
     ojo:'La cabina ancha con <b>puertas corredizas</b>, los patines altos y el rotor de cuatro palas. Los de policía llevan reflector y torreta de cámara bajo la nariz.',
     mx:'Es el helicóptero de la <b>policía</b> en varias ciudades — el grupo Cóndores de la Ciudad de México es el más conocido — y también de la Fuerza Aérea.'},
  },
  tuyaOjo:'Lo que más se encarga', tuyaT:'La réplica de tu propia aeronave',
  tuyaSub:'Es lo que más piden: el helicóptero que vuelas o que operas, con <b>sus colores, su número y su matrícula</b>. Sirve de regalo de retiro, de reconocimiento, de pieza de recepción o de obsequio a un cliente.',
  tuyaLista:[
   'Mándale fotos de la aeronave: los dos costados, la nariz y la cola.',
   'Si tiene logotipo o número de unidad, una foto de cerca — se pinta a mano.',
   'Él te dice si el modelo ya tiene molde o hay que prepararlo, y cuánto cambia el tiempo.',
   'Se puede hacer una pieza o una flota completa, todas iguales.',
  ],
  ctaTuya:'Pedir la de tu matrícula',
  piePolicia:'Bell 412 de la policía, con su número de unidad.',
  pieFam:'Con placa en la base: el nombre del dueño, bajo su propia aeronave.',
  procT:'Cómo se hace una', procN:'TALLER',
  procSub:'No es un juguete pintado: es una pieza fundida, lijada, montada y decorada a mano, una por una.',
  pieTaller:'Piezas fundidas esperando montaje y pintura, en el taller.',
  pasos:[
   ['El molde','De cada modelo se prepara un molde. Si ya existe, el encargo empieza aquí; si es un modelo nuevo, este es el paso que más tiempo toma.'],
   ['La colada','Resina en el molde, y a curar. Salen fuselaje, rotores, patines y piezas pequeñas por separado.'],
   ['Lijado y montaje','Cada pieza se lija a mano hasta que la forma queda limpia, y se monta con su rotor, su tren y su pedestal.'],
   ['Pintura y decoración','La librea, el número y la matrícula se pintan y se aplican a mano. Es lo que hace que se reconozca la aeronave y no solo el modelo.'],
  ],
  conT:'Dile cuál quieres',
  conSub:'Con el modelo y una foto de la librea alcanza para que te diga tiempo y precio. Contesta él.',
  formT:'Pide tu réplica', fNombre:'NOMBRE', fModelo:'MODELO', fLibrea:'LIBREA Y MATRÍCULA',
  phNombre:'Cómo te llamas', phModelo:'Ej. Airbus H125, Bell 407, Mi-17',
  phLibrea:'Colores, número de unidad, matrícula… o dime que te mando fotos',
  formNota:'Se abre WhatsApp con el mensaje ya escrito. Después le mandas las fotos por ahí mismo.',
  formBtn:'Enviar por WhatsApp',
  waSaludo:'Hola, vi la página de Heliescala.',
  waNombre:'Soy', waModelo:'Quiero una réplica de', waLibrea:'Librea y matrícula',
  faltaWa:'Todavía no hay número de WhatsApp cargado en la página.',
 },
 en:{
  marcaSub:'HANDMADE IN MEXICO',
  navCat:'Catalogue', navTuya:'Your aircraft', navProc:'How it is made', navEnv:'Shipping', navGal:'Gallery',
  visorAyuda:'CLICK THE PHOTO FOR FULL SIZE · ← → TO MOVE',
  kWa:'WHATSAPP', kMail:'EMAIL',
  otroIdioma:'Español',
  fichasNota:'<b>{desde}</b> is the starting point, not the price list: the final figure depends on the model, the size and how much the markings involve — a plain grey fuselage is not the same job as a full livery with crest, unit number and registration. Every order is quoted before work starts.',

  envT:'Where it goes', envN:'DELIVERY & SHIPPING',
  envSub:'In <b>Mexico City and the State of Mexico</b> he hands it to you in person, at no cost. Anywhere else in the country it travels by <b>DHL</b>, shipping charged separately: it leaves packed in a rigid box, with its tracking number.',
  envZonas:[
   ['01','Handed over in person','Mexico City · State of Mexico','No charge'],
   ['02','Central','Hidalgo · Morelos · Puebla · Tlaxcala · Querétaro · Guanajuato · San Luis Potosí · Michoacán','@envZ2'],
   ['03','West and north','Jalisco · Colima · Nayarit · Aguascalientes · Zacatecas · Durango · Sinaloa · Coahuila · Nuevo León · Tamaulipas · Chihuahua · Sonora','@envZ3'],
   ['04','South, southeast and the peninsulas','Guerrero · Oaxaca · Veracruz · Chiapas · Tabasco · Campeche · Yucatán · Quintana Roo · Baja California · Baja California Sur','@envZ4'],
  ],
  envNota:'Shipping is charged separately and quoted by DHL on the packed box: a replica weighs little but takes up room, and couriers charge by volume, not by weight. Order several pieces and they travel in one box, sharing the shipping.',

  galT:'More pieces', galN:'GALLERY',
  galSub:'The workshop and what comes out of it: the production table, raw parts, complete batches, and an exhibition hall with pieces of his on display.',
  galeria:[
   ['fotos/museo.jpg','<b>On display.</b> Pieces of his on pedestals in an exhibition hall, behind the rope.'],
   ['fotos/produccion.jpg','<b>The production table.</b> Fuselages in primer waiting for sanding, assembly and paint. This is how every order starts.'],
   ['fotos/fila.jpg','<b>A full batch.</b> Different models moving along together, each at its own stage.'],
   ['fotos/flota6.jpg','<b>Six identical.</b> A fleet order: same model, same camouflage, same paint, one by one.'],
   ['fotos/bruto-1.jpg','<b>Straight out of the mould.</b> The raw part, unsanded and unpainted, on the bench.'],
   ['fotos/bruto-2.jpg','<b>Fitted by hand.</b> Fuselage and tail separate, sandpaper and glue beside them. Everything is trial-fitted before it is joined.'],
   ['fotos/trio.jpg','<b>Three pieces together.</b> Rescue, air ambulance and transport, from the same batch.'],
   ['fotos/flota.jpg','<b>Work in progress.</b> Fuselages in a row, waiting for assembly and paint.'],
   ['fotos/policia.jpg','<b>Police Bell 412.</b> Unit number painted by hand.'],
  ],
  heroOjo:'Resin replicas · made to order',
  heroT1:'Almost any helicopter,', heroT2:'to scale and built by hand.',
  heroSub:'Airbus, Bell, Mi-17, Super Puma… cast in resin, assembled and painted by hand. Every model comes from its own mould, and the livery, unit number and registration are painted one by one.',
  ctaPedir:'Order a replica', ctaVer:'See the catalogue',
  dModelos:'26', kModelos:'In the catalogue', dResina:'Resin', kResina:'Material', kEscala:'Scales', kBase:'WORKSHOP',
  pieHero:'Three finished pieces: air ambulance, rescue and Super Puma.',
  catT:'Some of the ones he has built', catN:'CATALOGUE',
  catSub:'Twenty-six real pieces of his, each in the livery its original wore: Airbus, Bell, Agusta, Mil and even a fixed-wing. Civil, rescue, Navy, Air Force, Police and the US presidential machine. If yours is not here, it gets built: the mould and the markings are prepared for each order.',
  piezas:[
   ['h145','Airbus H145','fotos/h145.jpg','Fenestron, skid gear and a black and white corporate livery.',['AIRBUS','TWIN'],'h145'],
   ['h145a','Airbus H145 · display','fotos/h145-airbus.jpg','Display version in Airbus blue, on a pedestal.',['AIRBUS','DISPLAY'],'h145'],
   ['sgm','AS350 / H125 · air ambulance','fotos/sgm.jpg','Medical-services red, with stretcher and steps. One of the most requested.',['AIRBUS','AIR MEDICAL'],'h125'],
   ['mi17','Mi-17','fotos/mi17.jpg','The Russian transport, in grey. Five-blade rotor and fixed gear.',['MIL','TRANSPORT'],'mi17'],
   ['marina','Panther · Navy','fotos/marina.jpg','Three pieces from the same batch, in Mexican naval livery.',['NAVY','BATCH'],'panther'],
   ['rescate','Rescue · AESSA livery','fotos/rescate.jpg','A pair in red and yellow with emergency floats and high skids.',['RESCUE','PAIR'],''],
   ['bell407','SLP government · XC-PSI','fotos/bell407.jpg','Two units in blue and grey, registration and crest painted by hand.',['GOVERNMENT','PAIR'],''],
   ['policiapar','Bell 412 · Police','fotos/policia-par.jpg','The police fleet, in blue and white, ready to deliver.',['POLICE','FLEET'],'bell412'],
   ['marineone','US presidential · green and white','fotos/marineone.jpg','The most recognisable livery in the world: dark green, white belly and «UNITED STATES OF AMERICA» down the side.',['USA','PRESIDENTIAL'],''],
   ['xamvr','Airbus H145 · XA-MVR','fotos/xamvr.jpg','Corporate twin in blue over white, with its Mexican registration and flag painted by hand.',['AIRBUS','REGISTRATION'],'h145'],
   ['grandnew','AgustaWestland Grand New · XB-HFY','fotos/grandnew.jpg','Metallic silver finish with the model name lettered on the nose.',['AGUSTA','EXECUTIVE'],''],
   ['aessa-mcm','AESSA rescue · XA-MCM','fotos/aessa-mcm.jpg','Red and yellow with the rescue livery arrows and the registration under the cabin.',['RESCUE','REGISTRATION'],''],
   ['aessa-jgh','AESSA rescue · XA-JGH','fotos/aessa-jgh.jpg','The second machine of the same fleet, with its own registration. They are built identical and told apart by the number.',['RESCUE','FLEET'],''],
   ['fam-uma','Mexican Air Force · MX-UMA','fotos/fam-uma.jpg','White with the green and red stripe, the crest and the registration. One of the most heavily lettered pieces.',['AIR FORCE','REGISTRATION'],'bell412'],
   ['fam-412','Bell 412 · Air Force, camouflage','fotos/fam-412.jpg','Grey and white disruptive camouflage, with «FUERZA AÉREA MEXICANA» across the cabin roof.',['AIR FORCE','CAMOUFLAGE'],'bell412'],
   ['fam-sp','Super Puma · Air Force 1006','fotos/fam-sp.jpg','Light grey with its unit number, retractable gear and a four-blade rotor.',['AIR FORCE','TRANSPORT'],''],
   ['fam-mi17','Mi-17 · Mexican Air Force','fotos/fam-mi17.jpg','The Russian transport in grey, five-blade rotor, fixed gear and Air Force markings.',['AIR FORCE','TRANSPORT'],'mi17'],
   ['camo-verde','Super Puma · green camouflage','fotos/camo-verde.jpg','Military green and brown camouflage, with serial number and crest on the cabin.',['MILITARY','CAMOUFLAGE'],''],
   ['camo-gris','Cougar · grey camouflage','fotos/camo-gris.jpg','Grey and white patches over the whole fuselage, with its side sponsons.',['MILITARY','CAMOUFLAGE'],''],
   ['marina-cruz','Panther · Navy, medical','fotos/marina-cruz.jpg','Naval grey with «MARINA» and the red cross of the medical service, fenestron in the tail.',['NAVY','MEDICAL'],'panther'],
   ['fenestron','Twin with fenestron · blue and white','fotos/fenestron.jpg','Blue fin with the tail rotor buried inside it, and a white belly. Corporate livery.',['FENESTRON','CORPORATE'],''],
   ['xaecj','Corporate · XA-ECJ','fotos/xaecj.jpg','White with green and yellow flashes, carrying the operator\u2019s flag and registration.',['CIVIL','REGISTRATION'],''],
   ['policia-2','Police · Cóndores 01','fotos/policia-2.jpg','Two blue machines from the same fleet, with unit number and crest.',['POLICE','PAIR'],'bell412'],
   ['as350-grande','Red single · large format','fotos/as350-grande.jpg','One of the largest pieces he has built, with skids, steps and doors picked out.',['LARGE FORMAT','CIVIL'],'h125'],
   ['bell-camo','Light military · camouflage','fotos/bell-camo.jpg','Two-blade rotor with a stabiliser bar, high skids and red and white tail blades.',['MILITARY','LIGHT'],''],
   ['avion','Fixed-wing twin','fotos/avion.jpg','Not everything is a helicopter: he builds aeroplanes too. Twin turboprop transport, in military green.',['FIXED WING','TRANSPORT'],''],
  ],
  fichas:[['regla','SCALES','escalas'],['reloj','LEAD TIME','tiempo'],['caja','SHIPPING','envio'],['etiqueta','FROM','desde']],
  verFicha:'See the data sheet',
  fpRepT:'The replica', fpCta:'Order this one', fpDe:'of', fpRepD:'Built to order, in whatever livery you ask for: the one in the photo, your operator\u2019s, or your own.',
  fpSpec:{motor:'Engine', rotor:'Rotor', peso:'Max weight', cap:'Capacity', vel:'Cruise', alc:'Range'},
  fpBl:{usos:'What it is used for', ojo:'How to recognise it', mx:'In Mexico'},
  fpPend:'Exact model to be confirmed with the workshop.',
  modelos:{
   h145:{fab:'Airbus Helicopters', n:'H145 (BK117 D-3)',
     r:'Airbus\u2019 best-selling light twin for emergency work. Square cabin with rear clamshell doors, a fenestron in the tail and, since 2020, a bearingless five-blade rotor: 150 kg more useful load and far less noise.',
     sp:{motor:'2 × Safran Arriel 2E', rotor:'5 blades · fenestron', cap:'Up to 10 passengers', vel:'241 km/h', alc:'≈ 650 km'},
     usos:'Air ambulance, police, search and rescue, corporate transport and offshore. It is the one you see when a medical helicopter lands on a motorway.',
     ojo:'The <b>fenestron</b> — the tail rotor buried in the fin — and the <b>five blades</b> on the main rotor. Four blades with a fenestron means a pre-2020 H145.',
     mx:'It flies with private air-medical operators and government agencies; the Airbus display version is one of the most requested pieces.'},
   h125:{fab:'Airbus Helicopters', n:'H125 / AS350 Écureuil',
     r:'The single-engine workhorse. Light, simple to maintain and with a power-to-weight ratio that makes it unbeatable at altitude: in 2005 an AS350 B3 landed and took off from the summit of Everest, at 8,848 m — the record still stands.',
     sp:{motor:'1 × Safran Arriel 2D (952 shp)', rotor:'3 blades', peso:'2,250 kg', cap:'1 pilot + 6', vel:'252 km/h', alc:'≈ 630 km'},
     usos:'Aerial work, power-line jobs, firefighting, air ambulance, sightseeing and surveillance. Wherever there are mountains, there is an Écureuil.',
     ojo:'The narrow silhouette, the <b>three-blade rotor</b> and the exhaust exiting high, behind the rotor. Air-ambulance ones carry a stretcher and a side step.',
     mx:'One of the most common types in the country: medical services, state governments, aerial-work companies and tour operators.'},
   mi17:{fab:'Mil (Russia)', n:'Mi-17 / Mi-8MTV',
     r:'The truck of the air. A medium-heavy transport, mechanically rugged and built to operate where there is no hangar and no runway. Together with its predecessor the Mi-8, it is the most-produced helicopter in history.',
     sp:{motor:'2 × Klimov TV3-117 (≈2,070 shp)', rotor:'5 blades · 3-blade tail rotor', peso:'13,000 kg', cap:'Up to 24 passengers', vel:'225 km/h', alc:'≈ 580 km'},
     usos:'Troop and cargo transport, firefighting with a bambi bucket, evacuation and disaster relief.',
     ojo:'The <b>size</b>, the clamshell doors at the tail, the round windows and the fixed three-leg landing gear. It looks like nothing western.',
     mx:'The Mexican Air Force has operated Mi-17s since the nineties, and they are the ones you see in floods and hurricanes.'},
   panther:{fab:'Airbus Helicopters', n:'AS565 MBe Panther',
     r:'The naval version of the Dauphin: twin-engine, foldable to fit a ship\u2019s hangar and equipped to work over water. It is the navy\u2019s shipborne helicopter.',
     sp:{motor:'2 × Safran Arriel 2N', rotor:'4 blades · fenestron', peso:'4,500 kg', vel:'≈ 305 km/h', alc:'≈ 780 km'},
     usos:'Anti-submarine and anti-surface warfare, maritime surveillance, interdiction, and search and rescue at sea.',
     ojo:'The <b>fenestron</b> and the tall fin with a T-tail, plus the retractable gear and the sensor probe. Tail and blades fold.',
     mx:'The <b>Mexican Navy</b> received ten AS565 MBe between 2016 and 2017, and they operate from its ships.'},
   bell412:{fab:'Bell', n:'Bell 412',
     r:'A medium twin derived from the legendary Huey, with a four-blade rotor. A big cabin, two engines and familiar mechanics made it the standard for police and civil-protection work.',
     sp:{motor:'2 × Pratt &amp; Whitney (Twin-Pac)', rotor:'4 blades', peso:'5,534 kg', cap:'1 pilot + 14', vel:'228 km/h', alc:'≈ 669 km'},
     usos:'Police patrol, rescue, personnel transport, firefighting and offshore runs.',
     ojo:'The wide cabin with <b>sliding doors</b>, the tall skids and the four-blade rotor. Police ones carry a searchlight and a camera turret under the nose.',
     mx:'It is the police helicopter in several cities — Mexico City\u2019s Cóndores unit is the best known — and also flies with the Air Force.'},
  },
  tuyaOjo:'The most requested', tuyaT:'A replica of your own aircraft',
  tuyaSub:'It is what people ask for most: the helicopter you fly or operate, in <b>its colours, its unit number and its registration</b>. It works as a retirement gift, an award, a reception piece or a present for a client.',
  tuyaLista:[
   'Send him photos of the aircraft: both sides, the nose and the tail.',
   'If it carries a logo or unit number, a close-up — it is painted by hand.',
   'He tells you whether the model already has a mould or one has to be made, and how that changes the lead time.',
   'One piece or a whole matching fleet.',
  ],
  ctaTuya:'Order yours',
  piePolicia:'Police Bell 412, with its unit number.',
  pieFam:'With a plaque on the base: the owner’s name, under his own aircraft.',
  procT:'How one is made', procN:'WORKSHOP',
  procSub:'It is not a painted toy: it is a cast piece, sanded, assembled and decorated by hand, one at a time.',
  pieTaller:'Cast parts waiting for assembly and paint, at the workshop.',
  pasos:[
   ['The mould','A mould is prepared for each model. If it already exists, the order starts here; if the model is new, this is the step that takes longest.'],
   ['The pour','Resin into the mould, then cure. Fuselage, rotors, skids and small parts come out separately.'],
   ['Sanding and assembly','Every part is sanded by hand until the shape is clean, then assembled with its rotor, gear and pedestal.'],
   ['Paint and markings','Livery, unit number and registration are painted and applied by hand. That is what makes it recognisable as the aircraft, not just the model.'],
  ],
  conT:'Tell him which one you want',
  conSub:'The model and a photo of the livery are enough for him to quote time and price. He answers.',
  formT:'Order your replica', fNombre:'NAME', fModelo:'MODEL', fLibrea:'LIVERY AND REGISTRATION',
  phNombre:'Your name', phModelo:'e.g. Airbus H125, Bell 407, Mi-17',
  phLibrea:'Colours, unit number, registration… or just say you will send photos',
  formNota:'WhatsApp opens with the message already written. You send the photos right there.',
  formBtn:'Send over WhatsApp',
  waSaludo:'Hello, I saw the Heliescala page.',
  waNombre:'I am', waModelo:'I want a replica of', waLibrea:'Livery and registration',
  faltaWa:'No WhatsApp number has been loaded into the page yet.',
 }
};
