// El vocabulario de alemán y el tema de Partizip. Vive aquí y no dentro de una
// app porque lo usan DOS: `Aleman/vocabulario.html`, que es donde estaba, y la
// pantalla de Alemán del dashboard. Copiarlo en las dos era la duplicación de
// siempre: cambiar una palabra en un sitio dejaba el otro mintiendo.
//
//   cats  las 21 secciones, con su etiqueta y su emoji
//   voc   las 479 palabras: {art, de, es, ex, cat}
//           `art` es el artículo (der/die/das) o '-' si no lo lleva, y de ahí sale
//           el color con el que se pinta el género sin tener que leerlo
//   partizip  el único tema de gramática que se queda en el dashboard, por secciones
const ALEMAN_VOCAB = {
  cats: {
    saludos: {label:'Saludos', icon:'\ud83d\udc4b'},
    numeros: {label:'N\u00fameros', icon:'\ud83d\udd22'},
    colores: {label:'Colores', icon:'\ud83c\udfa8'},
    tiempo: {label:'Tiempo', icon:'\ud83d\udcc5'},
    familia: {label:'Familia', icon:'\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67'},
    cuerpo: {label:'Cuerpo', icon:'\ud83e\udec0'},
    ropa: {label:'Ropa', icon:'\ud83d\udc55'},
    comida: {label:'Comida', icon:'\ud83c\udf7d\ufe0f'},
    casa: {label:'Casa', icon:'\ud83c\udfe0'},
    ciudad: {label:'Ciudad', icon:'\ud83c\udfd9\ufe0f'},
    trabajo: {label:'Trabajo', icon:'\ud83d\udcbc'},
    naturaleza: {label:'Naturaleza', icon:'\ud83c\udf3f'},
    verbos: {label:'Verbos', icon:'\u2699\ufe0f'},
    adjetivos: {label:'Adjetivos', icon:'\ud83c\udfaf'},
    viaje: {label:'Viajes', icon:'\u2708\ufe0f'},
    emociones: {label:'Emociones', icon:'\ud83d\ude0a'},
    tecnologia: {label:'Tecnolog\u00eda', icon:'\ud83d\udcf1'},
    animales: {label:'Animales', icon:'\ud83d\udc3e'},
    compras: {label:'Compras', icon:'\ud83d\uded2'},
    escuela: {label:'Escuela', icon:'\ud83c\udf93'},
    adverbios: {label:'Adverbios', icon:'\u23f1\ufe0f'},
  },
  voc: [
    // SALUDOS
    {art:'-',de:'Hallo',es:'Hola',ex:'Hallo! Wie geht\'s?',cat:'saludos'},
    {art:'-',de:'Guten Morgen',es:'Buenos d\u00edas',ex:'Guten Morgen! Haben Sie gut geschlafen?',cat:'saludos'},
    {art:'-',de:'Guten Tag',es:'Buenos d\u00edas / Buenas tardes',ex:'Guten Tag, Frau M\u00fcller.',cat:'saludos'},
    {art:'-',de:'Guten Abend',es:'Buenas noches (saludo)',ex:'Guten Abend, wie war Ihr Tag?',cat:'saludos'},
    {art:'-',de:'Gute Nacht',es:'Buenas noches (despedida)',ex:'Gute Nacht! Schlaf gut.',cat:'saludos'},
    {art:'-',de:'Tsch\u00fcss / Auf Wiedersehen',es:'Adi\u00f3s / Hasta luego',ex:'Tsch\u00fcss! Bis morgen!',cat:'saludos'},
    {art:'-',de:'Bitte',es:'Por favor / De nada',ex:'K\u00f6nnen Sie mir helfen, bitte?',cat:'saludos'},
    {art:'-',de:'Danke / Danke sch\u00f6n',es:'Gracias / Muchas gracias',ex:'Danke sch\u00f6n f\u00fcr Ihre Hilfe!',cat:'saludos'},
    {art:'-',de:'Entschuldigung',es:'Disculpe / Perd\u00f3n',ex:'Entschuldigung, wo ist der Bahnhof?',cat:'saludos'},
    {art:'-',de:'Es tut mir leid',es:'Lo siento',ex:'Es tut mir leid, ich habe einen Fehler gemacht.',cat:'saludos'},
    {art:'-',de:'Ja / Nein',es:'S\u00ed / No',ex:'Ja, ich spreche Deutsch. Nein, danke.',cat:'saludos'},
    {art:'-',de:'Wie hei\u00dfen Sie?',es:'\u00bfC\u00f3mo se llama usted?',ex:'Wie hei\u00dfen Sie? \u2014 Ich hei\u00dfe Ana.',cat:'saludos'},
    {art:'-',de:'Woher kommen Sie?',es:'\u00bfDe d\u00f3nde es usted?',ex:'Woher kommen Sie? \u2014 Aus Mexiko.',cat:'saludos'},
    {art:'-',de:'Wie geht es Ihnen?',es:'\u00bfC\u00f3mo est\u00e1 usted?',ex:'Wie geht es Ihnen? \u2014 Gut, danke!',cat:'saludos'},
    {art:'-',de:'Ich verstehe nicht',es:'No entiendo',ex:'Entschuldigung, ich verstehe nicht. K\u00f6nnen Sie das wiederholen?',cat:'saludos'},
    {art:'-',de:'Sprechen Sie Englisch?',es:'\u00bfHabla ingl\u00e9s?',ex:'Sprechen Sie Englisch? Mein Deutsch ist noch nicht gut.',cat:'saludos'},
    {art:'-',de:'Wie war dein Tag?',es:'\u00bfC\u00f3mo estuvo tu d\u00eda?',ex:'Hallo! Wie war dein Tag?',cat:'saludos'},
    {art:'-',de:'Viel Gl\u00fcck!',es:'\u00a1Buena suerte!',ex:'Viel Gl\u00fcck bei der Pr\u00fcfung!',cat:'saludos'},
    {art:'-',de:'Alles Gute!',es:'\u00a1Todo lo mejor! / \u00a1Que te vaya bien!',ex:'Alles Gute zum Geburtstag!',cat:'saludos'},
    {art:'-',de:'Herzlichen Gl\u00fcckwunsch!',es:'\u00a1Felicidades!',ex:'Herzlichen Gl\u00fcckwunsch zur neuen Arbeit!',cat:'saludos'},
    {art:'-',de:'Prost! / Zum Wohl!',es:'\u00a1Salud!',ex:'Prost! Auf unsere Freundschaft!',cat:'saludos'},
    {art:'-',de:'Guten Appetit!',es:'\u00a1Buen provecho!',ex:'Guten Appetit! Lass es dir schmecken.',cat:'saludos'},
    {art:'-',de:'Willkommen!',es:'\u00a1Bienvenido/a!',ex:'Willkommen in Deutschland!',cat:'saludos'},
    {art:'-',de:'Sch\u00f6n, dich/Sie kennenzulernen',es:'Un placer conocerte/conocerle',ex:'Sch\u00f6n, Sie kennenzulernen, Herr Klein.',cat:'saludos'},
    // NÚMEROS
    {art:'-',de:'null',es:'cero (0)',ex:'Meine Nummer ist null-vier-...',cat:'numeros'},
    {art:'-',de:'eins / ein',es:'uno (1)',ex:'Ich habe ein Kind.',cat:'numeros'},
    {art:'-',de:'zwei',es:'dos (2)',ex:'Ich brauche zwei Tickets.',cat:'numeros'},
    {art:'-',de:'drei',es:'tres (3)',ex:'In drei Tagen fahre ich nach Berlin.',cat:'numeros'},
    {art:'-',de:'vier',es:'cuatro (4)',ex:'Ich wohne im vierten Stock.',cat:'numeros'},
    {art:'-',de:'f\u00fcnf',es:'cinco (5)',ex:'Die Besprechung ist um f\u00fcnf Uhr.',cat:'numeros'},
    {art:'-',de:'sechs',es:'seis (6)',ex:'Ich arbeite sechs Stunden am Tag.',cat:'numeros'},
    {art:'-',de:'sieben',es:'siete (7)',ex:'Die Woche hat sieben Tage.',cat:'numeros'},
    {art:'-',de:'acht',es:'ocho (8)',ex:'Ich stehe um acht Uhr auf.',cat:'numeros'},
    {art:'-',de:'neun',es:'nueve (9)',ex:'Er ist neun Jahre alt.',cat:'numeros'},
    {art:'-',de:'zehn',es:'diez (10)',ex:'Ich lerne seit zehn Monaten Deutsch.',cat:'numeros'},
    {art:'-',de:'elf',es:'once (11)',ex:'Der Zug kommt um elf Uhr.',cat:'numeros'},
    {art:'-',de:'zw\u00f6lf',es:'doce (12)',ex:'Wir haben zw\u00f6lf Monate im Jahr.',cat:'numeros'},
    {art:'-',de:'f\u00fcnfzehn',es:'quince (15)',ex:'In f\u00fcnfzehn Minuten bin ich da.',cat:'numeros'},
    {art:'-',de:'zwanzig',es:'veinte (20)',ex:'Das kostet zwanzig Euro.',cat:'numeros'},
    {art:'-',de:'drei\u00dfig',es:'treinta (30)',ex:'Ich bin drei\u00dfig Jahre alt.',cat:'numeros'},
    {art:'-',de:'vierzig',es:'cuarenta (40)',ex:'Die Reise dauert vierzig Minuten.',cat:'numeros'},
    {art:'-',de:'f\u00fcnfzig',es:'cincuenta (50)',ex:'F\u00fcnfzig Prozent ist die H\u00e4lfte.',cat:'numeros'},
    {art:'-',de:'sechzig',es:'sesenta (60)',ex:'Eine Stunde hat sechzig Minuten.',cat:'numeros'},
    {art:'-',de:'siebzig',es:'setenta (70)',ex:'Mein Opa ist siebzig Jahre alt.',cat:'numeros'},
    {art:'-',de:'achtzig',es:'ochenta (80)',ex:'Das Auto f\u00e4hrt achtzig km/h.',cat:'numeros'},
    {art:'-',de:'neunzig',es:'noventa (90)',ex:'Neunzig Prozent der Sch\u00fcler haben bestanden.',cat:'numeros'},
    {art:'-',de:'hundert',es:'cien (100)',ex:'Das Buch hat hundert Seiten.',cat:'numeros'},
    {art:'-',de:'tausend',es:'mil (1000)',ex:'Die Miete ist tausend Euro.',cat:'numeros'},
    {art:'die',de:'Million',es:'mill\u00f3n',ex:'Berlin hat \u00fcber drei Millionen Einwohner.',cat:'numeros'},
    {art:'-',de:'erste / zweite',es:'primero / segundo',ex:'Ich wohne im ersten Stock.',cat:'numeros'},
    {art:'-',de:'halb',es:'medio / mitad',ex:'Es ist halb zehn.',cat:'numeros'},
    {art:'das',de:'Prozent',es:'el porcentaje',ex:'F\u00fcnfzig Prozent sind genug.',cat:'numeros'},
    {art:'das',de:'Paar',es:'el par',ex:'Ich brauche ein Paar neue Schuhe.',cat:'numeros'},
    // COLORES
    {art:'-',de:'rot',es:'rojo',ex:'Das Auto ist rot.',cat:'colores'},
    {art:'-',de:'blau',es:'azul',ex:'Der Himmel ist blau.',cat:'colores'},
    {art:'-',de:'gr\u00fcn',es:'verde',ex:'Das Gras ist gr\u00fcn.',cat:'colores'},
    {art:'-',de:'gelb',es:'amarillo',ex:'Die Banane ist gelb.',cat:'colores'},
    {art:'-',de:'schwarz',es:'negro',ex:'Ich trage ein schwarzes Hemd.',cat:'colores'},
    {art:'-',de:'wei\u00df',es:'blanco',ex:'Die Wand ist wei\u00df.',cat:'colores'},
    {art:'-',de:'grau',es:'gris',ex:'Der Himmel ist grau heute.',cat:'colores'},
    {art:'-',de:'orange',es:'naranja',ex:'Die Orange ist orange.',cat:'colores'},
    {art:'-',de:'braun',es:'marr\u00f3n / caf\u00e9',ex:'Der Tisch ist braun.',cat:'colores'},
    {art:'-',de:'lila / violett',es:'morado / violeta',ex:'Sie tr\u00e4gt ein lila Kleid.',cat:'colores'},
    {art:'-',de:'rosa / pink',es:'rosa',ex:'Die Blumen sind rosa.',cat:'colores'},
    {art:'-',de:'t\u00fcrkis',es:'turquesa',ex:'Das Meer ist t\u00fcrkis.',cat:'colores'},
    {art:'-',de:'silber',es:'plateado',ex:'Ihr Auto ist silber.',cat:'colores'},
    {art:'-',de:'gold / golden',es:'dorado',ex:'Der Ring ist golden.',cat:'colores'},
    {art:'-',de:'bunt',es:'colorido / multicolor',ex:'Das Bild ist sehr bunt.',cat:'colores'},
    {art:'-',de:'hell / dunkel',es:'claro / oscuro',ex:'Ich mag helle Farben, nicht dunkle.',cat:'colores'},
    // TIEMPO
    {art:'der',de:'Montag',es:'lunes',ex:'Am Montag habe ich Deutschkurs.',cat:'tiempo'},
    {art:'der',de:'Dienstag',es:'martes',ex:'Am Dienstag arbeite ich von zu Hause.',cat:'tiempo'},
    {art:'der',de:'Mittwoch',es:'mi\u00e9rcoles',ex:'Mittwoch ist mein freier Tag.',cat:'tiempo'},
    {art:'der',de:'Donnerstag',es:'jueves',ex:'Am Donnerstag gehe ich ins Fitnessstudio.',cat:'tiempo'},
    {art:'der',de:'Freitag',es:'viernes',ex:'Freitag ist mein Lieblingstag!',cat:'tiempo'},
    {art:'der',de:'Samstag',es:'s\u00e1bado',ex:'Am Samstag schlafe ich lang.',cat:'tiempo'},
    {art:'der',de:'Sonntag',es:'domingo',ex:'Am Sonntag essen wir zusammen.',cat:'tiempo'},
    {art:'der',de:'Januar',es:'enero',ex:'Im Januar ist es sehr kalt.',cat:'tiempo'},
    {art:'der',de:'Februar',es:'febrero',ex:'Im Februar gibt es Karneval.',cat:'tiempo'},
    {art:'der',de:'M\u00e4rz',es:'marzo',ex:'Im M\u00e4rz beginnt der Fr\u00fchling.',cat:'tiempo'},
    {art:'der',de:'April',es:'abril',ex:'Im April regnet es oft.',cat:'tiempo'},
    {art:'der',de:'Mai',es:'mayo',ex:'Im Mai bl\u00fchen die Blumen.',cat:'tiempo'},
    {art:'der',de:'Juni',es:'junio',ex:'Im Juni ist es warm.',cat:'tiempo'},
    {art:'der',de:'Juli',es:'julio',ex:'Im Juli fahren wir in Urlaub.',cat:'tiempo'},
    {art:'der',de:'August',es:'agosto',ex:'Im August ist Hochsommer.',cat:'tiempo'},
    {art:'der',de:'September',es:'septiembre',ex:'Im September beginnt die Schule.',cat:'tiempo'},
    {art:'der',de:'Oktober',es:'octubre',ex:'Im Oktober gibt es das Oktoberfest.',cat:'tiempo'},
    {art:'der',de:'November',es:'noviembre',ex:'Im November wird es dunkel.',cat:'tiempo'},
    {art:'der',de:'Dezember',es:'diciembre',ex:'Im Dezember feiern wir Weihnachten.',cat:'tiempo'},
    {art:'der',de:'Fr\u00fchling',es:'primavera',ex:'Im Fr\u00fchling wird es w\u00e4rmer.',cat:'tiempo'},
    {art:'der',de:'Sommer',es:'verano',ex:'Im Sommer fahre ich ans Meer.',cat:'tiempo'},
    {art:'der',de:'Herbst',es:'oto\u00f1o',ex:'Im Herbst fallen die Bl\u00e4tter.',cat:'tiempo'},
    {art:'der',de:'Winter',es:'invierno',ex:'Im Winter schneit es in Deutschland.',cat:'tiempo'},
    {art:'-',de:'heute / gestern / morgen',es:'hoy / ayer / ma\u00f1ana',ex:'Heute lerne ich, gestern habe ich gearbeitet.',cat:'tiempo'},
    {art:'die',de:'Woche',es:'la semana',ex:'Diese Woche habe ich viel zu tun.',cat:'tiempo'},
    {art:'der',de:'Monat',es:'el mes',ex:'N\u00e4chsten Monat fahre ich nach Berlin.',cat:'tiempo'},
    {art:'das',de:'Jahr',es:'el a\u00f1o',ex:'Dieses Jahr lerne ich viel Deutsch.',cat:'tiempo'},
    {art:'das',de:'Wochenende',es:'el fin de semana',ex:'Was machst du am Wochenende?',cat:'tiempo'},
    {art:'der',de:'Feiertag',es:'el d\u00eda festivo',ex:'Morgen ist ein Feiertag.',cat:'tiempo'},
    {art:'der',de:'Termin',es:'la cita / el turno',ex:'Ich habe einen Termin um 15 Uhr.',cat:'tiempo'},
    {art:'der',de:'Kalender',es:'el calendario',ex:'Ich schreibe alles in meinen Kalender.',cat:'tiempo'},
    // FAMILIA
    {art:'die',de:'Mutter',es:'la madre',ex:'Meine Mutter kommt aus Mexiko.',cat:'familia'},
    {art:'der',de:'Vater',es:'el padre',ex:'Mein Vater arbeitet als Ingenieur.',cat:'familia'},
    {art:'die',de:'Schwester',es:'la hermana',ex:'Ich habe eine \u00e4ltere Schwester.',cat:'familia'},
    {art:'der',de:'Bruder',es:'el hermano',ex:'Mein Bruder studiert in Berlin.',cat:'familia'},
    {art:'die',de:'Gro\u00dfmutter / Oma',es:'la abuela',ex:'Meine Oma macht den besten Kuchen.',cat:'familia'},
    {art:'der',de:'Gro\u00dfvater / Opa',es:'el abuelo',ex:'Mein Opa ist 78 Jahre alt.',cat:'familia'},
    {art:'die',de:'Tante',es:'la t\u00eda',ex:'Meine Tante wohnt in M\u00fcnchen.',cat:'familia'},
    {art:'der',de:'Onkel',es:'el t\u00edo',ex:'Mein Onkel hat drei Kinder.',cat:'familia'},
    {art:'die',de:'Tochter',es:'la hija',ex:'Ihre Tochter ist sehr klug.',cat:'familia'},
    {art:'der',de:'Sohn',es:'el hijo',ex:'Sein Sohn lernt Deutsch.',cat:'familia'},
    {art:'das',de:'Kind',es:'el ni\u00f1o/hijo',ex:'Das Kind spielt im Garten.',cat:'familia'},
    {art:'der',de:'Mann / Ehemann',es:'el esposo/marido',ex:'Mein Mann arbeitet in der Stadt.',cat:'familia'},
    {art:'die',de:'Frau / Ehefrau',es:'la esposa/mujer',ex:'Seine Frau ist \u00c4rztin.',cat:'familia'},
    {art:'der',de:'Freund / die Freundin',es:'el amigo / la novia',ex:'Mein Freund kommt heute.',cat:'familia'},
    {art:'pl.',de:'Eltern',es:'los padres',ex:'Meine Eltern wohnen in Puebla.',cat:'familia'},
    {art:'pl.',de:'Geschwister',es:'los hermanos (en general)',ex:'Ich habe zwei Geschwister.',cat:'familia'},
    {art:'der',de:'Cousin / die Cousine',es:'el primo / la prima',ex:'Meine Cousine besucht mich im Sommer.',cat:'familia'},
    {art:'der',de:'Neffe / die Nichte',es:'el sobrino / la sobrina',ex:'Mein Neffe ist erst zwei Jahre alt.',cat:'familia'},
    {art:'die',de:'Schwiegermutter / der Schwiegervater',es:'la suegra / el suegro',ex:'Meine Schwiegermutter kocht sehr gut.',cat:'familia'},
    {art:'das',de:'Baby',es:'el beb\u00e9',ex:'Das Baby schl\u00e4ft gerade.',cat:'familia'},
    {art:'das',de:'Enkelkind',es:'el nieto / la nieta',ex:'Sie hat vier Enkelkinder.',cat:'familia'},
    {art:'der/die',de:'Partner / Partnerin',es:'la pareja (novio/a, c\u00f3nyuge)',ex:'Das ist mein Partner.',cat:'familia'},
    {art:'-',de:'verheiratet / ledig',es:'casado / soltero',ex:'Ich bin nicht verheiratet, ich bin ledig.',cat:'familia'},
    // CUERPO
    {art:'der',de:'Kopf',es:'la cabeza',ex:'Ich habe Kopfschmerzen.',cat:'cuerpo'},
    {art:'das',de:'Auge (pl. Augen)',es:'el ojo',ex:'Er hat blaue Augen.',cat:'cuerpo'},
    {art:'das',de:'Ohr (pl. Ohren)',es:'el o\u00eddo / la oreja',ex:'Meine Ohren tun weh.',cat:'cuerpo'},
    {art:'die',de:'Nase',es:'la nariz',ex:'Meine Nase ist verstopft.',cat:'cuerpo'},
    {art:'der',de:'Mund',es:'la boca',ex:'\u00d6ffne bitte den Mund.',cat:'cuerpo'},
    {art:'der',de:'Zahn (pl. Z\u00e4hne)',es:'el diente',ex:'Ich muss zum Zahnarzt.',cat:'cuerpo'},
    {art:'der',de:'Hals',es:'el cuello / la garganta',ex:'Ich habe Halsschmerzen.',cat:'cuerpo'},
    {art:'die',de:'Schulter',es:'el hombro',ex:'Meine Schulter tut weh.',cat:'cuerpo'},
    {art:'der',de:'Arm',es:'el brazo',ex:'Er hat sich den Arm gebrochen.',cat:'cuerpo'},
    {art:'die',de:'Hand (pl. H\u00e4nde)',es:'la mano',ex:'Gib mir bitte die Hand.',cat:'cuerpo'},
    {art:'der',de:'Finger',es:'el dedo',ex:'Ich habe mir den Finger geschnitten.',cat:'cuerpo'},
    {art:'der',de:'Bauch',es:'el abdomen / la barriga',ex:'Ich habe Bauchschmerzen.',cat:'cuerpo'},
    {art:'der',de:'R\u00fccken',es:'la espalda',ex:'Mein R\u00fccken schmerzt nach dem Sport.',cat:'cuerpo'},
    {art:'das',de:'Bein',es:'la pierna',ex:'Er hat sich das Bein verletzt.',cat:'cuerpo'},
    {art:'der',de:'Fu\u00df (pl. F\u00fc\u00dfe)',es:'el pie',ex:'Meine F\u00fc\u00dfe sind m\u00fcde.',cat:'cuerpo'},
    {art:'das',de:'Herz',es:'el coraz\u00f3n',ex:'Sein Herz schl\u00e4gt schnell.',cat:'cuerpo'},
    {art:'das',de:'Haar (pl. Haare)',es:'el pelo / cabello',ex:'Sie hat lange Haare.',cat:'cuerpo'},
    {art:'das',de:'Gesicht',es:'la cara / el rostro',ex:'Er hat ein freundliches Gesicht.',cat:'cuerpo'},
    {art:'die',de:'Zunge',es:'la lengua',ex:'Zeig mir deine Zunge.',cat:'cuerpo'},
    {art:'die',de:'Haut',es:'la piel',ex:'Ihre Haut ist sehr empfindlich.',cat:'cuerpo'},
    {art:'das',de:'Knie',es:'la rodilla',ex:'Mein Knie tut weh.',cat:'cuerpo'},
    {art:'der',de:'Ellbogen',es:'el codo',ex:'Ich habe mir den Ellbogen gesto\u00dfen.',cat:'cuerpo'},
    {art:'die',de:'H\u00fcfte',es:'la cadera',ex:'Sie hat Schmerzen in der H\u00fcfte.',cat:'cuerpo'},
    // ROPA
    {art:'das',de:'Hemd',es:'la camisa',ex:'Er tr\u00e4gt ein wei\u00dfes Hemd.',cat:'ropa'},
    {art:'die',de:'Hose',es:'el pantal\u00f3n',ex:'Ich brauche eine neue Hose.',cat:'ropa'},
    {art:'das',de:'Kleid',es:'el vestido',ex:'Sie tr\u00e4gt ein rotes Kleid.',cat:'ropa'},
    {art:'der',de:'Rock',es:'la falda',ex:'Der Rock ist zu kurz.',cat:'ropa'},
    {art:'die',de:'Jacke',es:'la chaqueta / el saco',ex:'Nimm eine Jacke mit, es ist kalt!',cat:'ropa'},
    {art:'der',de:'Mantel',es:'el abrigo',ex:'Im Winter brauche ich einen Mantel.',cat:'ropa'},
    {art:'der',de:'Pullover',es:'el su\u00e9ter',ex:'Dieser Pullover ist sehr warm.',cat:'ropa'},
    {art:'die',de:'Socken (pl.)',es:'los calcetines',ex:'Ich habe meine Socken vergessen.',cat:'ropa'},
    {art:'die',de:'Schuhe (pl.)',es:'los zapatos',ex:'Diese Schuhe sind sehr bequem.',cat:'ropa'},
    {art:'die',de:'M\u00fctze',es:'el gorro / la gorra',ex:'Im Winter trage ich eine M\u00fctze.',cat:'ropa'},
    {art:'der',de:'Schal',es:'la bufanda',ex:'Mein Schal ist aus Wolle.',cat:'ropa'},
    {art:'die',de:'Handschuhe (pl.)',es:'los guantes',ex:'Im Winter brauche ich Handschuhe.',cat:'ropa'},
    {art:'die',de:'Gr\u00f6\u00dfe',es:'la talla',ex:'Welche Gr\u00f6\u00dfe haben Sie? \u2014 Gr\u00f6\u00dfe M.',cat:'ropa'},
    {art:'der',de:'Anzug',es:'el traje',ex:'Er tr\u00e4gt einen Anzug zur Arbeit.',cat:'ropa'},
    {art:'die',de:'Krawatte',es:'la corbata',ex:'Diese Krawatte passt gut zum Hemd.',cat:'ropa'},
    {art:'die',de:'Unterw\u00e4sche',es:'la ropa interior',ex:'Ich muss Unterw\u00e4sche kaufen.',cat:'ropa'},
    {art:'pl.',de:'Sandalen',es:'las sandalias',ex:'Im Sommer trage ich Sandalen.',cat:'ropa'},
    {art:'pl.',de:'Stiefel',es:'las botas',ex:'Im Winter brauche ich warme Stiefel.',cat:'ropa'},
    {art:'der',de:'Badeanzug',es:'el traje de ba\u00f1o',ex:'Ich habe meinen Badeanzug vergessen.',cat:'ropa'},
    {art:'die',de:'Brille',es:'los anteojos / las gafas',ex:'Ohne Brille sehe ich nichts.',cat:'ropa'},
    {art:'die',de:'Uhr',es:'el reloj',ex:'Seine Uhr war ein Geschenk.',cat:'ropa'},
    {art:'die',de:'Tasche / Handtasche',es:'el bolso',ex:'Meine Handtasche ist sehr praktisch.',cat:'ropa'},
    // COMIDA
    {art:'das',de:'Brot',es:'el pan',ex:'Zum Fr\u00fchst\u00fcck esse ich Brot.',cat:'comida'},
    {art:'die',de:'Butter',es:'la mantequilla',ex:'Das Brot mit Butter ist lecker.',cat:'comida'},
    {art:'der',de:'K\u00e4se',es:'el queso',ex:'Deutschland hat viele K\u00e4sesorten.',cat:'comida'},
    {art:'das',de:'Ei (pl. Eier)',es:'el huevo',ex:'Ich esse gern R\u00fchreier.',cat:'comida'},
    {art:'das',de:'Fleisch',es:'la carne',ex:'Ich esse kein Fleisch \u2014 ich bin Vegetarier.',cat:'comida'},
    {art:'der',de:'Fisch',es:'el pescado',ex:'Gebratener Fisch ist lecker.',cat:'comida'},
    {art:'das',de:'Gem\u00fcse',es:'la verdura',ex:'Ich esse viel Gem\u00fcse.',cat:'comida'},
    {art:'das',de:'Obst',es:'la fruta',ex:'T\u00e4glich Obst ist gesund.',cat:'comida'},
    {art:'die',de:'Kartoffel',es:'la papa / patata',ex:'Deutsche lieben Kartoffeln.',cat:'comida'},
    {art:'der',de:'Reis',es:'el arroz',ex:'Ich esse Reis mit Gem\u00fcse.',cat:'comida'},
    {art:'die',de:'Nudeln (pl.)',es:'la pasta',ex:'Nudeln mit Tomatensauce mag ich sehr.',cat:'comida'},
    {art:'die',de:'Suppe',es:'la sopa',ex:'Im Winter esse ich gern Suppe.',cat:'comida'},
    {art:'der',de:'Kaffee',es:'el caf\u00e9',ex:'Morgens trinke ich immer Kaffee.',cat:'comida'},
    {art:'der',de:'Tee',es:'el t\u00e9',ex:'Ich trinke lieber Tee als Kaffee.',cat:'comida'},
    {art:'das',de:'Wasser',es:'el agua',ex:'Ich trinke t\u00e4glich 2 Liter Wasser.',cat:'comida'},
    {art:'das',de:'Bier',es:'la cerveza',ex:'Ein Bier, bitte!',cat:'comida'},
    {art:'der',de:'Wein',es:'el vino',ex:'Ein Glas Wein am Abend.',cat:'comida'},
    {art:'der',de:'Saft',es:'el jugo',ex:'Ich m\u00f6chte einen Orangensaft.',cat:'comida'},
    {art:'die',de:'Milch',es:'la leche',ex:'Kinder trinken viel Milch.',cat:'comida'},
    {art:'die',de:'Schokolade',es:'el chocolate',ex:'Deutsche Schokolade ist weltbekannt.',cat:'comida'},
    {art:'das',de:'Fr\u00fchst\u00fcck',es:'el desayuno',ex:'Was gibt es zum Fr\u00fchst\u00fcck?',cat:'comida'},
    {art:'das',de:'Mittagessen',es:'el almuerzo',ex:'Das Mittagessen ist um 13 Uhr.',cat:'comida'},
    {art:'das',de:'Abendessen',es:'la cena',ex:'Wir kochen zusammen das Abendessen.',cat:'comida'},
    {art:'der',de:'Nachtisch / das Dessert',es:'el postre',ex:'Zum Nachtisch gibt es Eis.',cat:'comida'},
    {art:'der',de:'Kuchen',es:'el pastel',ex:'Meine Oma backt einen Kuchen.',cat:'comida'},
    {art:'der',de:'Zucker',es:'el az\u00facar',ex:'Ich nehme keinen Zucker im Kaffee.',cat:'comida'},
    {art:'das',de:'Salz',es:'la sal',ex:'Die Suppe braucht mehr Salz.',cat:'comida'},
    {art:'der',de:'Pfeffer',es:'la pimienta',ex:'Etwas Pfeffer, bitte.',cat:'comida'},
    {art:'das',de:'\u00d6l',es:'el aceite',ex:'Oliven\u00f6l ist sehr gesund.',cat:'comida'},
    {art:'der',de:'Honig',es:'la miel',ex:'Tee mit Honig schmeckt gut.',cat:'comida'},
    {art:'-',de:'s\u00fc\u00df / sauer / salzig / scharf',es:'dulce / \u00e1cido / salado / picante',ex:'Das Essen ist zu scharf f\u00fcr mich.',cat:'comida'},
    {art:'der/die',de:'Vegetarier / Veganer',es:'vegetariano / vegano',ex:'Ich bin seit einem Jahr Veganer.',cat:'comida'},
    // CASA
    {art:'die',de:'Wohnung',es:'el apartamento',ex:'Ich suche eine Wohnung in M\u00fcnchen.',cat:'casa'},
    {art:'das',de:'Haus',es:'la casa',ex:'Wir wohnen in einem gro\u00dfen Haus.',cat:'casa'},
    {art:'das',de:'Zimmer',es:'la habitaci\u00f3n / cuarto',ex:'Mein Zimmer ist klein aber gem\u00fctlich.',cat:'casa'},
    {art:'die',de:'K\u00fcche',es:'la cocina',ex:'Ich koche jeden Abend in der K\u00fcche.',cat:'casa'},
    {art:'das',de:'Badezimmer',es:'el ba\u00f1o',ex:'Das Badezimmer ist im ersten Stock.',cat:'casa'},
    {art:'das',de:'Wohnzimmer',es:'la sala',ex:'Wir sitzen im Wohnzimmer.',cat:'casa'},
    {art:'das',de:'Schlafzimmer',es:'el dormitorio',ex:'Mein Schlafzimmer ist ruhig.',cat:'casa'},
    {art:'die',de:'T\u00fcr',es:'la puerta',ex:'Mach bitte die T\u00fcr zu.',cat:'casa'},
    {art:'das',de:'Fenster',es:'la ventana',ex:'Das Fenster ist offen.',cat:'casa'},
    {art:'der',de:'Tisch',es:'la mesa',ex:'Das Essen steht auf dem Tisch.',cat:'casa'},
    {art:'der',de:'Stuhl',es:'la silla',ex:'Setz dich bitte auf den Stuhl.',cat:'casa'},
    {art:'das',de:'Bett',es:'la cama',ex:'Ich gehe um 22 Uhr ins Bett.',cat:'casa'},
    {art:'der',de:'K\u00fchlschrank',es:'el refrigerador',ex:'Der K\u00fchlschrank ist leer.',cat:'casa'},
    {art:'die',de:'Waschmaschine',es:'la lavadora',ex:'Ich muss die W\u00e4sche waschen.',cat:'casa'},
    {art:'die',de:'Miete',es:'el alquiler',ex:'Die Miete ist 900 Euro pro Monat.',cat:'casa'},
    {art:'der',de:'Garten',es:'el jard\u00edn',ex:'Die Kinder spielen im Garten.',cat:'casa'},
    {art:'der',de:'Balkon',es:'el balc\u00f3n',ex:'Wir fr\u00fchst\u00fccken auf dem Balkon.',cat:'casa'},
    {art:'der',de:'Keller',es:'el s\u00f3tano',ex:'Das Fahrrad steht im Keller.',cat:'casa'},
    {art:'das',de:'Dach',es:'el techo (tejado)',ex:'Das Dach ist rot.',cat:'casa'},
    {art:'die',de:'Wand',es:'la pared',ex:'An der Wand h\u00e4ngt ein Bild.',cat:'casa'},
    {art:'der',de:'Boden',es:'el suelo / piso',ex:'Der Boden ist aus Holz.',cat:'casa'},
    {art:'die',de:'Lampe',es:'la l\u00e1mpara',ex:'Mach bitte die Lampe an.',cat:'casa'},
    {art:'das',de:'Sofa',es:'el sof\u00e1',ex:'Ich sitze gern auf dem Sofa.',cat:'casa'},
    {art:'das',de:'Regal',es:'la estanter\u00eda / repisa',ex:'Die B\u00fccher stehen im Regal.',cat:'casa'},
    {art:'der',de:'Teppich',es:'la alfombra',ex:'Der Teppich im Wohnzimmer ist neu.',cat:'casa'},
    {art:'der/die',de:'Nachbar / Nachbarin',es:'el vecino / la vecina',ex:'Mein Nachbar ist sehr freundlich.',cat:'casa'},
    {art:'der',de:'Vermieter',es:'el arrendador',ex:'Der Vermieter hat die Miete erh\u00f6ht.',cat:'casa'},
    {art:'der',de:'Mieter',es:'el inquilino',ex:'Die Mieter zahlen jeden Monat.',cat:'casa'},
    // CIUDAD
    {art:'die',de:'Stadt',es:'la ciudad',ex:'Berlin ist eine tolle Stadt.',cat:'ciudad'},
    {art:'die',de:'Stra\u00dfe',es:'la calle',ex:'Die Stra\u00dfe ist sehr breit.',cat:'ciudad'},
    {art:'der',de:'Bahnhof',es:'la estaci\u00f3n de tren',ex:'Der Hauptbahnhof ist gro\u00df.',cat:'ciudad'},
    {art:'die',de:'U-Bahn',es:'el metro',ex:'Ich fahre mit der U-Bahn zur Arbeit.',cat:'ciudad'},
    {art:'die',de:'S-Bahn',es:'el metro r\u00e1pido/tren urbano',ex:'Die S-Bahn ist schneller.',cat:'ciudad'},
    {art:'der',de:'Bus',es:'el autob\u00fas',ex:'Der Bus kommt um 8 Uhr.',cat:'ciudad'},
    {art:'der',de:'Zug',es:'el tren',ex:'Der Zug nach M\u00fcnchen f\u00e4hrt um 10 Uhr ab.',cat:'ciudad'},
    {art:'das',de:'Flugzeug',es:'el avi\u00f3n',ex:'Wir fliegen mit dem Flugzeug.',cat:'ciudad'},
    {art:'das',de:'Auto',es:'el auto',ex:'Ich fahre jeden Tag mit dem Auto.',cat:'ciudad'},
    {art:'die',de:'Apotheke',es:'la farmacia',ex:'Die Apotheke ist um die Ecke.',cat:'ciudad'},
    {art:'das',de:'Krankenhaus',es:'el hospital',ex:'Das Krankenhaus ist 2 km entfernt.',cat:'ciudad'},
    {art:'der',de:'Supermarkt',es:'el supermercado',ex:'Ich gehe zum Supermarkt einkaufen.',cat:'ciudad'},
    {art:'die',de:'Schule',es:'la escuela',ex:'Die Kinder gehen um 8 Uhr zur Schule.',cat:'ciudad'},
    {art:'die',de:'Universit\u00e4t',es:'la universidad',ex:'Ich studiere an der Universit\u00e4t Berlin.',cat:'ciudad'},
    {art:'die',de:'Post',es:'el correo / la oficina postal',ex:'Ich schicke ein Paket bei der Post.',cat:'ciudad'},
    {art:'die',de:'Bank',es:'el banco',ex:'Ich muss Geld zur Bank bringen.',cat:'ciudad'},
    {art:'-',de:'links / rechts',es:'izquierda / derecha',ex:'Biegen Sie links ab!',cat:'ciudad'},
    {art:'-',de:'geradeaus',es:'recto / de frente',ex:'Gehen Sie geradeaus, dann links.',cat:'ciudad'},
    {art:'die',de:'Ampel',es:'el sem\u00e1foro',ex:'An der Ampel links abbiegen.',cat:'ciudad'},
    {art:'die',de:'Kreuzung',es:'el cruce',ex:'An der Kreuzung ist die Bank.',cat:'ciudad'},
    {art:'die',de:'Br\u00fccke',es:'el puente',ex:'Die Br\u00fccke f\u00fchrt \u00fcber die Spree.',cat:'ciudad'},
    {art:'der',de:'Platz',es:'la plaza',ex:'Der Alexanderplatz ist bekannt.',cat:'ciudad'},
    {art:'das',de:'Rathaus',es:'el ayuntamiento',ex:'Das Rathaus ist im Stadtzentrum.',cat:'ciudad'},
    {art:'die',de:'Kirche',es:'la iglesia',ex:'Die Kirche ist sehr alt.',cat:'ciudad'},
    {art:'der',de:'Park',es:'el parque',ex:'Wir machen einen Spaziergang im Park.',cat:'ciudad'},
    {art:'der',de:'Parkplatz',es:'el estacionamiento',ex:'Der Parkplatz ist voll.',cat:'ciudad'},
    {art:'das',de:'Taxi',es:'el taxi',ex:'Ich nehme ein Taxi zum Flughafen.',cat:'ciudad'},
    {art:'das',de:'Fahrrad',es:'la bicicleta',ex:'Ich fahre mit dem Fahrrad zur Arbeit.',cat:'ciudad'},
    {art:'der/die',de:'Fu\u00dfg\u00e4nger / Fu\u00dfg\u00e4ngerin',es:'el/la peat\u00f3n',ex:'Fu\u00dfg\u00e4nger haben hier Vorrang.',cat:'ciudad'},
    {art:'der',de:'Verkehr',es:'el tr\u00e1fico',ex:'Der Verkehr ist heute sehr stark.',cat:'ciudad'},
    {art:'der',de:'Stau',es:'el atasco / embotellamiento',ex:'Wir stehen im Stau.',cat:'ciudad'},
    // TRABAJO
    {art:'die',de:'Arbeit',es:'el trabajo',ex:'Ich muss zur Arbeit.',cat:'trabajo'},
    {art:'das',de:'B\u00fcro',es:'la oficina',ex:'Ich arbeite im B\u00fcro.',cat:'trabajo'},
    {art:'der',de:'Beruf',es:'la profesi\u00f3n / el oficio',ex:'Was ist Ihr Beruf?',cat:'trabajo'},
    {art:'das',de:'Gehalt',es:'el salario',ex:'Mein Gehalt ist gut.',cat:'trabajo'},
    {art:'der/die',de:'Chef / Chefin',es:'el/la jefe/a',ex:'Mein Chef ist nett.',cat:'trabajo'},
    {art:'der/die',de:'Kollege / Kollegin',es:'el/la colega',ex:'Meine Kollegen sind hilfsbereit.',cat:'trabajo'},
    {art:'die',de:'Besprechung',es:'la reuni\u00f3n',ex:'Um 10 Uhr haben wir eine Besprechung.',cat:'trabajo'},
    {art:'der',de:'Urlaub',es:'las vacaciones',ex:'Im August mache ich Urlaub.',cat:'trabajo'},
    {art:'die',de:'Bewerbung',es:'la solicitud de empleo',ex:'Ich schicke meine Bewerbung ab.',cat:'trabajo'},
    {art:'der',de:'Lebenslauf',es:'el curr\u00edculum vitae',ex:'Mein Lebenslauf ist aktuell.',cat:'trabajo'},
    {art:'die',de:'Pr\u00fcfung',es:'el examen',ex:'Morgen habe ich meine Deutschpr\u00fcfung.',cat:'trabajo'},
    {art:'das',de:'Studium',es:'los estudios universitarios',ex:'Mein Studium dauert 3 Jahre.',cat:'trabajo'},
    {art:'der',de:'Kurs',es:'el curso',ex:'Ich besuche einen Deutschkurs.',cat:'trabajo'},
    {art:'das',de:'Praktikum',es:'la pr\u00e1ctica profesional / pasant\u00eda',ex:'Ich mache ein Praktikum bei Bosch.',cat:'trabajo'},
    {art:'der',de:'Vertrag',es:'el contrato',ex:'Ich habe den Vertrag unterschrieben.',cat:'trabajo'},
    {art:'die',de:'K\u00fcndigung',es:'el despido / la renuncia',ex:'Er hat die K\u00fcndigung bekommen.',cat:'trabajo'},
    {art:'die',de:'Teamarbeit',es:'el trabajo en equipo',ex:'Teamarbeit ist hier sehr wichtig.',cat:'trabajo'},
    {art:'der',de:'Feierabend',es:'el fin de la jornada laboral',ex:'Endlich Feierabend!',cat:'trabajo'},
    {art:'das',de:'Homeoffice',es:'el trabajo desde casa',ex:'Ich mache heute Homeoffice.',cat:'trabajo'},
    {art:'-',de:'Vollzeit / Teilzeit',es:'tiempo completo / parcial',ex:'Ich arbeite Teilzeit.',cat:'trabajo'},
    {art:'die',de:'Rente',es:'la pensi\u00f3n / jubilaci\u00f3n',ex:'Meine Oma bekommt eine gute Rente.',cat:'trabajo'},
    {art:'-',de:'arbeitslos',es:'desempleado',ex:'Er ist seit einem Monat arbeitslos.',cat:'trabajo'},
    // NATURALEZA
    {art:'die',de:'Sonne',es:'el sol',ex:'Die Sonne scheint heute.',cat:'naturaleza'},
    {art:'der',de:'Regen',es:'la lluvia',ex:'Es regnet den ganzen Tag.',cat:'naturaleza'},
    {art:'der',de:'Schnee',es:'la nieve',ex:'Im Winter gibt es viel Schnee.',cat:'naturaleza'},
    {art:'der',de:'Wind',es:'el viento',ex:'Der Wind ist stark heute.',cat:'naturaleza'},
    {art:'die',de:'Wolke',es:'la nube',ex:'Heute ist es bew\u00f6lkt.',cat:'naturaleza'},
    {art:'-',de:'warm / kalt / hei\u00df',es:'c\u00e1lido / fr\u00edo / caliente',ex:'Im Sommer ist es hei\u00df, im Winter kalt.',cat:'naturaleza'},
    {art:'-',de:'Es regnet',es:'Est\u00e1 lloviendo',ex:'Es regnet \u2014 nimm einen Regenschirm!',cat:'naturaleza'},
    {art:'-',de:'Es schneit',es:'Est\u00e1 nevando',ex:'Es schneit in Berlin.',cat:'naturaleza'},
    {art:'der',de:'Wald',es:'el bosque',ex:'Wir machen einen Spaziergang im Wald.',cat:'naturaleza'},
    {art:'der',de:'Fluss',es:'el r\u00edo',ex:'Die Donau ist ein gro\u00dfer Fluss.',cat:'naturaleza'},
    {art:'das',de:'Meer',es:'el mar',ex:'Im Sommer fahren wir ans Meer.',cat:'naturaleza'},
    {art:'der',de:'Berg',es:'la monta\u00f1a',ex:'Die Alpen sind sehr sch\u00f6ne Berge.',cat:'naturaleza'},
    {art:'die',de:'Temperatur',es:'la temperatura',ex:'Die Temperatur betr\u00e4gt 20 Grad.',cat:'naturaleza'},
    {art:'der',de:'Baum',es:'el \u00e1rbol',ex:'Vor dem Haus steht ein gro\u00dfer Baum.',cat:'naturaleza'},
    {art:'die',de:'Blume',es:'la flor',ex:'Sie schenkt mir immer Blumen.',cat:'naturaleza'},
    {art:'das',de:'Tier',es:'el animal',ex:'Welches Tier magst du am liebsten?',cat:'naturaleza'},
    {art:'der',de:'Himmel',es:'el cielo',ex:'Der Himmel ist heute klar.',cat:'naturaleza'},
    {art:'der',de:'Stern',es:'la estrella',ex:'Man kann die Sterne gut sehen.',cat:'naturaleza'},
    {art:'der',de:'Mond',es:'la luna',ex:'Der Mond ist heute voll.',cat:'naturaleza'},
    {art:'die',de:'Insel',es:'la isla',ex:'Wir verbringen den Urlaub auf einer Insel.',cat:'naturaleza'},
    {art:'der',de:'See',es:'el lago',ex:'Wir schwimmen im See.',cat:'naturaleza'},
    {art:'die',de:'W\u00fcste',es:'el desierto',ex:'Die W\u00fcste ist sehr trocken.',cat:'naturaleza'},
    {art:'die',de:'Umwelt',es:'el medio ambiente',ex:'Wir m\u00fcssen die Umwelt sch\u00fctzen.',cat:'naturaleza'},
    // VERBOS
    {art:'-',de:'sein',es:'ser / estar',ex:'Ich bin Mexikaner. Er ist m\u00fcde.',cat:'verbos'},
    {art:'-',de:'haben',es:'tener / haber',ex:'Ich habe einen Bruder.',cat:'verbos'},
    {art:'-',de:'machen',es:'hacer',ex:'Was machst du heute?',cat:'verbos'},
    {art:'-',de:'gehen',es:'ir / caminar',ex:'Ich gehe in die Schule.',cat:'verbos'},
    {art:'-',de:'kommen',es:'venir / llegar',ex:'Wann kommst du?',cat:'verbos'},
    {art:'-',de:'fahren',es:'ir (en veh\u00edculo)',ex:'Ich fahre mit dem Zug nach Berlin.',cat:'verbos'},
    {art:'-',de:'essen',es:'comer',ex:'Ich esse gern Pizza.',cat:'verbos'},
    {art:'-',de:'trinken',es:'beber',ex:'Ich trinke Kaffee.',cat:'verbos'},
    {art:'-',de:'schlafen',es:'dormir',ex:'Ich schlafe 8 Stunden.',cat:'verbos'},
    {art:'-',de:'arbeiten',es:'trabajar',ex:'Ich arbeite bei Bosch.',cat:'verbos'},
    {art:'-',de:'lernen',es:'aprender',ex:'Ich lerne jeden Tag Deutsch.',cat:'verbos'},
    {art:'-',de:'sprechen',es:'hablar',ex:'Ich spreche Deutsch und Spanisch.',cat:'verbos'},
    {art:'-',de:'verstehen',es:'entender',ex:'Ich verstehe diese Frage nicht.',cat:'verbos'},
    {art:'-',de:'wohnen',es:'vivir / residir',ex:'Ich wohne in Berlin.',cat:'verbos'},
    {art:'-',de:'kaufen',es:'comprar',ex:'Ich kaufe ein neues Handy.',cat:'verbos'},
    {art:'-',de:'schreiben',es:'escribir',ex:'Ich schreibe eine E-Mail.',cat:'verbos'},
    {art:'-',de:'lesen',es:'leer',ex:'Ich lese jeden Abend.',cat:'verbos'},
    {art:'-',de:'sehen',es:'ver',ex:'Ich sehe heute einen Film.',cat:'verbos'},
    {art:'-',de:'h\u00f6ren',es:'escuchar / o\u00edr',ex:'Ich h\u00f6re gern Musik.',cat:'verbos'},
    {art:'-',de:'helfen',es:'ayudar',ex:'Kannst du mir helfen?',cat:'verbos'},
    {art:'-',de:'wissen',es:'saber',ex:'Ich wei\u00df nicht.',cat:'verbos'},
    {art:'-',de:'m\u00f6chten',es:'quisiera / querer',ex:'Ich m\u00f6chte einen Kaffee.',cat:'verbos'},
    {art:'-',de:'brauchen',es:'necesitar',ex:'Ich brauche Hilfe.',cat:'verbos'},
    {art:'-',de:'fragen',es:'preguntar',ex:'Ich m\u00f6chte Sie etwas fragen.',cat:'verbos'},
    {art:'-',de:'antworten',es:'responder / contestar',ex:'Kannst du mir antworten?',cat:'verbos'},
    {art:'-',de:'geben',es:'dar',ex:'Kannst du mir das Salz geben?',cat:'verbos'},
    {art:'-',de:'nehmen',es:'tomar / coger',ex:'Ich nehme den Bus um 8 Uhr.',cat:'verbos'},
    {art:'-',de:'finden',es:'encontrar / opinar',ex:'Ich finde diesen Film gut.',cat:'verbos'},
    {art:'-',de:'suchen',es:'buscar',ex:'Ich suche meine Schl\u00fcssel.',cat:'verbos'},
    {art:'-',de:'spielen',es:'jugar',ex:'Die Kinder spielen im Park.',cat:'verbos'},
    {art:'-',de:'zeigen',es:'mostrar',ex:'Kannst du mir den Weg zeigen?',cat:'verbos'},
    {art:'-',de:'bringen',es:'traer / llevar',ex:'Kannst du mir das Buch bringen?',cat:'verbos'},
    {art:'-',de:'bleiben',es:'quedarse',ex:'Ich bleibe heute zu Hause.',cat:'verbos'},
    {art:'-',de:'anfangen / beginnen',es:'empezar',ex:'Der Kurs beginnt um 9 Uhr.',cat:'verbos'},
    {art:'-',de:'denken',es:'pensar',ex:'Ich denke oft an dich.',cat:'verbos'},
    {art:'-',de:'glauben',es:'creer',ex:'Ich glaube, das ist richtig.',cat:'verbos'},
    {art:'-',de:'m\u00f6gen',es:'gustar / apreciar',ex:'Ich mag diese Stadt.',cat:'verbos'},
    {art:'-',de:'lieben',es:'amar',ex:'Ich liebe meine Familie.',cat:'verbos'},
    {art:'-',de:'warten',es:'esperar',ex:'Ich warte auf den Bus.',cat:'verbos'},
    {art:'-',de:'\u00f6ffnen',es:'abrir',ex:'Kannst du das Fenster \u00f6ffnen?',cat:'verbos'},
    {art:'-',de:'schlie\u00dfen',es:'cerrar',ex:'Bitte schlie\u00dfen Sie die T\u00fcr.',cat:'verbos'},
    {art:'-',de:'bezahlen',es:'pagar',ex:'Ich m\u00f6chte bitte bezahlen.',cat:'verbos'},
    {art:'-',de:'bestellen',es:'pedir / ordenar',ex:'Ich bestelle einen Kaffee.',cat:'verbos'},
    {art:'-',de:'treffen',es:'encontrarse / reunirse',ex:'Wir treffen uns um 6 Uhr.',cat:'verbos'},
    {art:'-',de:'besuchen',es:'visitar',ex:'Ich besuche meine Eltern am Sonntag.',cat:'verbos'},
    // ADJETIVOS
    {art:'-',de:'gro\u00df / klein',es:'grande / peque\u00f1o',ex:'Berlin ist gro\u00df. Mein Zimmer ist klein.',cat:'adjetivos'},
    {art:'-',de:'gut / schlecht',es:'bueno / malo',ex:'Das Essen ist gut. Das Wetter ist schlecht.',cat:'adjetivos'},
    {art:'-',de:'sch\u00f6n / h\u00e4sslich',es:'bonito / feo',ex:'Diese Stadt ist sehr sch\u00f6n.',cat:'adjetivos'},
    {art:'-',de:'alt / jung / neu',es:'viejo / joven / nuevo',ex:'Das Haus ist alt. Ich bin jung.',cat:'adjetivos'},
    {art:'-',de:'schnell / langsam',es:'r\u00e1pido / lento',ex:'Der Zug ist schnell.',cat:'adjetivos'},
    {art:'-',de:'teuer / billig',es:'caro / barato',ex:'Das Hotel ist teuer aber sch\u00f6n.',cat:'adjetivos'},
    {art:'-',de:'leicht / schwer',es:'f\u00e1cil / dif\u00edcil / ligero / pesado',ex:'Deutsch ist schwer, aber sch\u00f6n.',cat:'adjetivos'},
    {art:'-',de:'voll / leer',es:'lleno / vac\u00edo',ex:'Der Zug ist voll.',cat:'adjetivos'},
    {art:'-',de:'m\u00fcde / wach',es:'cansado / despierto',ex:'Ich bin sehr m\u00fcde heute.',cat:'adjetivos'},
    {art:'-',de:'hungrig / satt',es:'hambriento / satisfecho',ex:'Ich bin hungrig. Haben Sie etwas zu essen?',cat:'adjetivos'},
    {art:'-',de:'krank / gesund',es:'enfermo / sano',ex:'Ich bin krank \u2014 ich muss zum Arzt.',cat:'adjetivos'},
    {art:'-',de:'gl\u00fccklich / traurig',es:'feliz / triste',ex:'Ich bin sehr gl\u00fccklich hier.',cat:'adjetivos'},
    {art:'-',de:'wichtig',es:'importante',ex:'Das ist sehr wichtig!',cat:'adjetivos'},
    {art:'-',de:'interessant',es:'interesante',ex:'Deutschland ist ein interessantes Land.',cat:'adjetivos'},
    {art:'-',de:'nett / freundlich',es:'simp\u00e1tico / amable',ex:'Die Deutschen sind nett.',cat:'adjetivos'},
    {art:'-',de:'einfach / kompliziert',es:'sencillo / complicado',ex:'Diese \u00dcbung ist ganz einfach.',cat:'adjetivos'},
    {art:'-',de:'laut / leise',es:'ruidoso / silencioso',ex:'Die Musik ist zu laut.',cat:'adjetivos'},
    {art:'-',de:'stark / schwach',es:'fuerte / d\u00e9bil',ex:'Der Kaffee ist sehr stark.',cat:'adjetivos'},
    {art:'-',de:'fr\u00fch / sp\u00e4t',es:'temprano / tarde',ex:'Es ist schon sp\u00e4t!',cat:'adjetivos'},
    {art:'-',de:'nah / weit',es:'cerca / lejos',ex:'Die Schule ist ganz nah.',cat:'adjetivos'},
    {art:'-',de:'richtig / falsch',es:'correcto / incorrecto',ex:'Deine Antwort ist richtig.',cat:'adjetivos'},
    {art:'-',de:'frei / besetzt',es:'libre / ocupado',ex:'Ist dieser Platz frei?',cat:'adjetivos'},
    {art:'-',de:'sauber / schmutzig',es:'limpio / sucio',ex:'Die K\u00fcche ist sauber.',cat:'adjetivos'},
    // VIAJES
    {art:'der',de:'Flughafen',es:'el aeropuerto',ex:'Das Flugzeug landet am Flughafen.',cat:'viaje'},
    {art:'das',de:'Ticket / die Fahrkarte',es:'el boleto',ex:'Wo kaufe ich ein Ticket?',cat:'viaje'},
    {art:'das',de:'Hotel',es:'el hotel',ex:'Ich habe ein Zimmer im Hotel reserviert.',cat:'viaje'},
    {art:'der',de:'Pass / Reisepass',es:'el pasaporte',ex:'Wo ist mein Reisepass?',cat:'viaje'},
    {art:'der',de:'Koffer',es:'la maleta',ex:'Mein Koffer ist sehr schwer.',cat:'viaje'},
    {art:'die',de:'Reservierung',es:'la reservaci\u00f3n',ex:'Ich habe eine Reservierung.',cat:'viaje'},
    {art:'-',de:'einchecken',es:'hacer check-in',ex:'Ich m\u00f6chte einchecken.',cat:'viaje'},
    {art:'die',de:'Touristeninformation',es:'la oficina de turismo',ex:'Die Touristeninformation ist am Hauptbahnhof.',cat:'viaje'},
    {art:'die',de:'Sehensw\u00fcrdigkeit',es:'el lugar tur\u00edstico / atracci\u00f3n',ex:'Das Brandenburger Tor ist eine bekannte Sehensw\u00fcrdigkeit.',cat:'viaje'},
    {art:'die',de:'Reise',es:'el viaje',ex:'Die Reise nach Deutschland war sch\u00f6n.',cat:'viaje'},
    {art:'-',de:'reisen',es:'viajar',ex:'Ich reise gern nach Europa.',cat:'viaje'},
    {art:'das',de:'Gep\u00e4ck',es:'el equipaje',ex:'Mein Gep\u00e4ck ist noch nicht angekommen.',cat:'viaje'},
    {art:'der',de:'Ausweis',es:'la identificaci\u00f3n',ex:'Zeigen Sie bitte Ihren Ausweis.',cat:'viaje'},
    {art:'die',de:'Grenze',es:'la frontera',ex:'Wir \u00fcberqueren die Grenze nach \u00d6sterreich.',cat:'viaje'},
    {art:'der/die',de:'Abflug / Ankunft',es:'la salida / la llegada (vuelo)',ex:'Der Abflug ist um 14 Uhr.',cat:'viaje'},
    {art:'die',de:'Versp\u00e4tung',es:'el retraso',ex:'Der Zug hat 20 Minuten Versp\u00e4tung.',cat:'viaje'},
    {art:'der',de:'Zoll',es:'la aduana',ex:'Wir m\u00fcssen durch den Zoll.',cat:'viaje'},
    {art:'die',de:'Landkarte / Karte',es:'el mapa',ex:'Hast du eine Karte von der Stadt?',cat:'viaje'},
    {art:'das',de:'Souvenir / Andenken',es:'el recuerdo (regalo)',ex:'Ich kaufe ein Souvenir f\u00fcr meine Mutter.',cat:'viaje'},
    {art:'die',de:'Jugendherberge',es:'el albergue juvenil',ex:'Wir \u00fcbernachten in einer Jugendherberge.',cat:'viaje'},
    // EMOCIONES
    {art:'-',de:'froh / fr\u00f6hlich',es:'contento / alegre',ex:'Ich bin froh, dich zu sehen.',cat:'emociones'},
    {art:'-',de:'w\u00fctend',es:'enojado / furioso',ex:'Er ist w\u00fctend auf seinen Bruder.',cat:'emociones'},
    {art:'-',de:'\u00e4ngstlich',es:'temeroso / asustado',ex:'Sie ist \u00e4ngstlich vor Hunden.',cat:'emociones'},
    {art:'-',de:'\u00fcberrascht',es:'sorprendido',ex:'Ich war sehr \u00fcberrascht von dem Geschenk.',cat:'emociones'},
    {art:'-',de:'gelangweilt',es:'aburrido (sentirse)',ex:'Die Kinder sind gelangweilt.',cat:'emociones'},
    {art:'-',de:'nerv\u00f6s',es:'nervioso',ex:'Ich bin nerv\u00f6s vor der Pr\u00fcfung.',cat:'emociones'},
    {art:'-',de:'verliebt',es:'enamorado',ex:'Sie sind sehr verliebt.',cat:'emociones'},
    {art:'-',de:'stolz',es:'orgulloso',ex:'Ich bin stolz auf dich.',cat:'emociones'},
    {art:'-',de:'eifers\u00fcchtig',es:'celoso',ex:'Er ist ein bisschen eifers\u00fcchtig.',cat:'emociones'},
    {art:'-',de:'entspannt',es:'relajado',ex:'Am Wochenende bin ich entspannt.',cat:'emociones'},
    {art:'-',de:'gestresst',es:'estresado',ex:'Ich bin heute sehr gestresst.',cat:'emociones'},
    {art:'-',de:'entt\u00e4uscht',es:'decepcionado',ex:'Ich bin entt\u00e4uscht von dem Ergebnis.',cat:'emociones'},
    {art:'-',de:'dankbar',es:'agradecido',ex:'Ich bin dir sehr dankbar.',cat:'emociones'},
    {art:'-',de:'neugierig',es:'curioso',ex:'Die Kinder sind sehr neugierig.',cat:'emociones'},
    {art:'-',de:'zufrieden',es:'satisfecho / contento',ex:'Ich bin zufrieden mit meiner Arbeit.',cat:'emociones'},
    {art:'-',de:'einsam',es:'solitario',ex:'Manchmal f\u00fchle ich mich einsam.',cat:'emociones'},
    // TECNOLOGÍA
    {art:'das',de:'Handy / Smartphone',es:'el celular',ex:'Mein Handy hat keinen Akku mehr.',cat:'tecnologia'},
    {art:'der',de:'Computer / Rechner',es:'la computadora',ex:'Ich arbeite am Computer.',cat:'tecnologia'},
    {art:'das',de:'Internet',es:'internet',ex:'Ohne Internet kann ich nicht arbeiten.',cat:'tecnologia'},
    {art:'die',de:'E-Mail',es:'el correo electr\u00f3nico',ex:'Ich schreibe eine E-Mail.',cat:'tecnologia'},
    {art:'das',de:'Passwort',es:'la contrase\u00f1a',ex:'Ich habe mein Passwort vergessen.',cat:'tecnologia'},
    {art:'die',de:'App',es:'la aplicaci\u00f3n',ex:'Ich habe eine neue App heruntergeladen.',cat:'tecnologia'},
    {art:'-',de:'herunterladen',es:'descargar',ex:'Kannst du mir die App herunterladen?',cat:'tecnologia'},
    {art:'der',de:'Akku',es:'la bater\u00eda',ex:'Der Akku ist fast leer.',cat:'tecnologia'},
    {art:'-',de:'aufladen',es:'cargar (bater\u00eda)',ex:'Ich muss mein Handy aufladen.',cat:'tecnologia'},
    {art:'das',de:'WLAN',es:'el wifi',ex:'Gibt es hier kostenloses WLAN?',cat:'tecnologia'},
    {art:'der',de:'Bildschirm',es:'la pantalla',ex:'Der Bildschirm ist kaputt.',cat:'tecnologia'},
    {art:'die',de:'Taste',es:'la tecla / el bot\u00f3n',ex:'Dr\u00fcck diese Taste.',cat:'tecnologia'},
    {art:'-',de:'klicken',es:'hacer clic',ex:'Klicken Sie hier, um fortzufahren.',cat:'tecnologia'},
    {art:'-',de:'speichern',es:'guardar (archivo)',ex:'Hast du das Dokument gespeichert?',cat:'tecnologia'},
    {art:'-',de:'l\u00f6schen',es:'borrar / eliminar',ex:'Ich habe die Nachricht gel\u00f6scht.',cat:'tecnologia'},
    {art:'die',de:'Nachricht',es:'el mensaje',ex:'Ich habe dir eine Nachricht geschickt.',cat:'tecnologia'},
    // ANIMALES
    {art:'der',de:'Hund',es:'el perro',ex:'Mein Hund hei\u00dft Bello.',cat:'animales'},
    {art:'die',de:'Katze',es:'el gato / la gata',ex:'Die Katze schl\u00e4ft den ganzen Tag.',cat:'animales'},
    {art:'der',de:'Vogel',es:'el p\u00e1jaro',ex:'Der Vogel singt sch\u00f6n.',cat:'animales'},
    {art:'das',de:'Pferd',es:'el caballo',ex:'Sie reitet gern auf dem Pferd.',cat:'animales'},
    {art:'die',de:'Kuh',es:'la vaca',ex:'Die Kuh gibt Milch.',cat:'animales'},
    {art:'das',de:'Schwein',es:'el cerdo',ex:'Das Schwein lebt auf dem Bauernhof.',cat:'animales'},
    {art:'das',de:'Huhn',es:'la gallina / el pollo',ex:'Das Huhn legt Eier.',cat:'animales'},
    {art:'die',de:'Maus',es:'el rat\u00f3n',ex:'Die Katze jagt die Maus.',cat:'animales'},
    {art:'der',de:'L\u00f6we',es:'el le\u00f3n',ex:'Der L\u00f6we ist der K\u00f6nig der Tiere.',cat:'animales'},
    {art:'der',de:'Elefant',es:'el elefante',ex:'Der Elefant ist sehr gro\u00df.',cat:'animales'},
    {art:'der',de:'Affe',es:'el mono',ex:'Der Affe klettert auf den Baum.',cat:'animales'},
    {art:'der',de:'B\u00e4r',es:'el oso',ex:'Im Zoo gibt es einen B\u00e4ren.',cat:'animales'},
    {art:'der',de:'Schmetterling',es:'la mariposa',ex:'Ein bunter Schmetterling fliegt vorbei.',cat:'animales'},
    {art:'der',de:'Fisch',es:'el pez',ex:'Im Aquarium schwimmen viele Fische.',cat:'animales'},
    // COMPRAS
    {art:'das',de:'Gesch\u00e4ft / der Laden',es:'la tienda',ex:'Das Gesch\u00e4ft \u00f6ffnet um 9 Uhr.',cat:'compras'},
    {art:'die',de:'Kasse',es:'la caja registradora',ex:'Bitte zahlen Sie an der Kasse.',cat:'compras'},
    {art:'der',de:'Rabatt',es:'el descuento',ex:'Es gibt 20% Rabatt.',cat:'compras'},
    {art:'das',de:'Angebot',es:'la oferta',ex:'Das ist ein gutes Angebot.',cat:'compras'},
    {art:'die',de:'Quittung',es:'el recibo',ex:'Kann ich eine Quittung bekommen?',cat:'compras'},
    {art:'das',de:'Bargeld',es:'el efectivo',ex:'Ich zahle lieber mit Bargeld.',cat:'compras'},
    {art:'die',de:'Kreditkarte',es:'la tarjeta de cr\u00e9dito',ex:'Akzeptieren Sie Kreditkarten?',cat:'compras'},
    {art:'-',de:'umtauschen',es:'cambiar / devolver (producto)',ex:'Ich m\u00f6chte diesen Pullover umtauschen.',cat:'compras'},
    {art:'-',de:'anprobieren',es:'probarse (ropa)',ex:'Darf ich das anprobieren?',cat:'compras'},
    {art:'-',de:'g\u00fcnstig',es:'barato / conveniente',ex:'Dieses Gesch\u00e4ft ist sehr g\u00fcnstig.',cat:'compras'},
    {art:'die',de:'Marke',es:'la marca',ex:'Welche Marke bevorzugst du?',cat:'compras'},
    {art:'der/die',de:'Verk\u00e4ufer / Verk\u00e4uferin',es:'el/la vendedor/a',ex:'Der Verk\u00e4ufer war sehr freundlich.',cat:'compras'},
    {art:'der',de:'Kundendienst',es:'el servicio al cliente',ex:'Ruf den Kundendienst an.',cat:'compras'},
    {art:'der',de:'Einkaufswagen',es:'el carrito de compras',ex:'Der Einkaufswagen ist voll.',cat:'compras'},
    {art:'die',de:'Einkaufsliste',es:'la lista de compras',ex:'Ich habe eine Einkaufsliste geschrieben.',cat:'compras'},
    // ESCUELA
    {art:'der/die',de:'Sch\u00fcler / Sch\u00fclerin',es:'el/la alumno/a',ex:'Die Sch\u00fclerin lernt sehr flei\u00dfig.',cat:'escuela'},
    {art:'das',de:'Klassenzimmer',es:'el sal\u00f3n de clase',ex:'Das Klassenzimmer ist hell.',cat:'escuela'},
    {art:'die',de:'Hausaufgabe',es:'la tarea',ex:'Ich mache meine Hausaufgaben.',cat:'escuela'},
    {art:'die',de:'Note',es:'la calificaci\u00f3n',ex:'Ich habe eine gute Note bekommen.',cat:'escuela'},
    {art:'das',de:'Buch',es:'el libro',ex:'Dieses Buch ist sehr interessant.',cat:'escuela'},
    {art:'das',de:'Heft',es:'el cuaderno',ex:'Schreib das in dein Heft.',cat:'escuela'},
    {art:'der',de:'Stift',es:'el bol\u00edgrafo / l\u00e1piz',ex:'Hast du einen Stift f\u00fcr mich?',cat:'escuela'},
    {art:'das',de:'W\u00f6rterbuch',es:'el diccionario',ex:'Ich benutze ein W\u00f6rterbuch.',cat:'escuela'},
    {art:'-',de:'\u00fcben',es:'practicar',ex:'Ich muss mehr Grammatik \u00fcben.',cat:'escuela'},
    {art:'-',de:'wiederholen',es:'repasar / repetir',ex:'K\u00f6nnen Sie das bitte wiederholen?',cat:'escuela'},
    {art:'der',de:'Fehler',es:'el error',ex:'Aus Fehlern lernt man.',cat:'escuela'},
    {art:'der',de:'Fortschritt',es:'el progreso',ex:'Du machst gute Fortschritte!',cat:'escuela'},
    // ADVERBIOS
    {art:'-',de:'immer',es:'siempre',ex:'Ich trinke immer Kaffee am Morgen.',cat:'adverbios'},
    {art:'-',de:'oft',es:'a menudo',ex:'Ich gehe oft ins Kino.',cat:'adverbios'},
    {art:'-',de:'manchmal',es:'a veces',ex:'Manchmal koche ich zu Hause.',cat:'adverbios'},
    {art:'-',de:'selten',es:'raramente',ex:'Ich fahre selten mit dem Auto.',cat:'adverbios'},
    {art:'-',de:'nie',es:'nunca',ex:'Ich trinke nie Alkohol.',cat:'adverbios'},
    {art:'-',de:'jetzt',es:'ahora',ex:'Ich muss jetzt gehen.',cat:'adverbios'},
    {art:'-',de:'gleich',es:'en seguida / ahora mismo',ex:'Ich komme gleich!',cat:'adverbios'},
    {art:'-',de:'bald',es:'pronto',ex:'Bis bald!',cat:'adverbios'},
    {art:'-',de:'schon',es:'ya',ex:'Ich habe das schon gemacht.',cat:'adverbios'},
    {art:'-',de:'noch',es:'todav\u00eda / a\u00fan',ex:'Ich bin noch hier.',cat:'adverbios'},
    {art:'-',de:'noch nicht',es:'todav\u00eda no',ex:'Ich habe noch nicht gegessen.',cat:'adverbios'},
    {art:'-',de:'sp\u00e4ter',es:'m\u00e1s tarde',ex:'Wir sprechen sp\u00e4ter dar\u00fcber.',cat:'adverbios'},
    {art:'-',de:'zuerst',es:'primero',ex:'Zuerst fr\u00fchst\u00fccke ich, dann arbeite ich.',cat:'adverbios'},
    {art:'-',de:'zuletzt / schlie\u00dflich',es:'por \u00faltimo / finalmente',ex:'Zuletzt r\u00e4umen wir die K\u00fcche auf.',cat:'adverbios'},
  ],

  // El tema de gramática. Cada sección puede traer una `tabla`, una `lista` de
  // tres columnas, una `comparativa` (lo que NO se dice / lo que sí), un `aviso`
  // naranja o un `truco` turquesa. Ninguna los lleva todos.
  partizip: {
    titulo: 'Partizip I y II',
    sub: 'Las dos formas de participio del alem\u00e1n: cu\u00e1l es cu\u00e1l, c\u00f3mo se forman y cu\u00e1ndo se usa cada una.',
    secciones: [
      { id:'que', ico:'\ud83e\udded', t:'Qu\u00e9 son, en una frase',
        cuerpo:'El alem\u00e1n tiene dos participios y no se parecen en nada. El <b>Partizip II</b> es el que usas todo el rato: es el que forma el pasado (<i>ich habe gegessen</i>) y la voz pasiva. El <b>Partizip I</b> es el que casi no vas a usar al hablar, pero aparece leyendo: convierte un verbo en adjetivo (<i>das lachende Kind</i>, el ni\u00f1o que r\u00ede).',
        aviso:'Si s\u00f3lo te quedas con una cosa: <b>Partizip I no es el gerundio espa\u00f1ol</b>. \u00abEstoy comiendo\u00bb NO se dice <s>ich bin essend</s>.',
      },
      { id:'p2form', ico:'\ud83d\udd28', t:'Partizip II \u2014 c\u00f3mo se forma',
        cuerpo:'Hay dos patrones seg\u00fan el tipo de verbo, y luego cuatro excepciones que cubren casi todos los casos raros.',
        tabla:{cols:['Tipo','Regla','Ejemplo'], filas:[
          ['Regulares (schwach)','ge + ra\u00edz + <b>t</b>','machen \u2192 <b>ge</b>mach<b>t</b>'],
          ['Irregulares (stark)','ge + ra\u00edz (a veces cambia) + <b>en</b>','gehen \u2192 <b>ge</b>gang<b>en</b>'],
          ['Mixtos','ge + ra\u00edz cambiada + <b>t</b>','bringen \u2192 <b>ge</b>brach<b>t</b>'],
        ]},
      },
      { id:'p2sinGe', ico:'\ud83d\udeab', t:'Los cuatro casos SIN ge-',
        cuerpo:'Aqu\u00ed es donde se equivoca todo el mundo. Estos verbos no llevan <b>ge-</b>:',
        lista:[
          ['Prefijo inseparable','be-, emp-, ent-, er-, ge-, miss-, ver-, zer-','besuchen \u2192 besucht \u00b7 verstehen \u2192 verstanden'],
          ['Verbos en -ieren','todos, sin excepci\u00f3n','studieren \u2192 studiert \u00b7 funktionieren \u2192 funktioniert'],
          ['Separables: el ge- va EN MEDIO','prefijo + ge + resto','aufstehen \u2192 auf<b>ge</b>standen \u00b7 einkaufen \u2192 ein<b>ge</b>kauft'],
          ['Con s\u00edlaba \u00e1tona inicial','poco frecuentes','trompeten \u2192 trompetet'],
        ],
        truco:'Regla pr\u00e1ctica: si la primera s\u00edlaba del infinitivo <b>no</b> lleva el acento, no lleva ge-. <i>be</i>SUchen s\u00ed, <i>AUF</i>stehen no.',
      },
      { id:'p2uso', ico:'\ud83c\udfaf', t:'Partizip II \u2014 para qu\u00e9 sirve',
        cuerpo:'Cuatro usos, y el primero es el 90% de las veces que lo vas a decir.',
        lista:[
          ['Perfekt \u2014 el pasado hablado','haben / sein + Partizip II, y el participio va al FINAL','Ich habe das Auto <b>repariert</b>.'],
          ['Plusquamperfekt','hatte / war + Partizip II','Ich hatte schon <b>gegessen</b>.'],
          ['Pasiva','werden + Partizip II','Das Auto wird <b>repariert</b>.'],
          ['Como adjetivo','se declina como cualquier adjetivo','das <b>reparierte</b> Auto'],
        ],
      },
      { id:'habenSein', ico:'\ud83d\udd00', t:'\u00bfhaben o sein?',
        cuerpo:'La duda de siempre al armar el Perfekt. La mayor\u00eda van con <b>haben</b>; <b>sein</b> es la lista corta, y por eso conviene aprenderse esa.',
        lista:[
          ['sein \u2014 movimiento de A a B','gehen, fahren, fliegen, kommen, laufen, reisen','Ich <b>bin</b> nach Berlin gefahren.'],
          ['sein \u2014 cambio de estado','aufstehen, einschlafen, aufwachen, sterben, wachsen','Er <b>ist</b> eingeschlafen.'],
          ['sein \u2014 los tres sueltos','sein, bleiben, werden','Ich <b>bin</b> m\u00fcde gewesen.'],
          ['haben \u2014 todo lo dem\u00e1s','y siempre que el verbo lleve objeto directo','Ich <b>habe</b> ein Auto gekauft.'],
        ],
        aviso:'Ojo con <i>fahren</i>: <b>ich bin</b> gefahren (yo fui, me mov\u00ed) pero <b>ich habe</b> das Auto gefahren (yo conduje el coche). Con objeto directo, haben.',
      },
      { id:'p1', ico:'\u2728', t:'Partizip I \u2014 la forma f\u00e1cil',
        cuerpo:'Se forma sin excepciones: <b>infinitivo + d</b>. Y ya est\u00e1.',
        tabla:{cols:['Verbo','Partizip I','C\u00f3mo se traduce'], filas:[
          ['lachen (re\u00edr)','lach<b>end</b>','que r\u00ede / riendo'],
          ['schlafen (dormir)','schlaf<b>end</b>','que duerme / durmiendo'],
          ['spielen (jugar)','spiel<b>end</b>','que juega / jugando'],
          ['sein (ser)','sei<b>end</b>','siendo \u2014 se usa poqu\u00edsimo'],
        ]},
      },
      { id:'p1uso', ico:'\ud83d\udcd6', t:'Partizip I \u2014 d\u00f3nde aparece',
        cuerpo:'Dos usos, y en los dos es una descripci\u00f3n, nunca un tiempo verbal.',
        lista:[
          ['Como adjetivo \u2014 se declina','delante del sustantivo, con su terminaci\u00f3n','das lachend<b>e</b> Kind \u00b7 ein schlafend<b>er</b> Hund'],
          ['Como adverbio \u2014 invariable','describe c\u00f3mo se hace algo','Sie kam <b>lachend</b> herein. (entr\u00f3 riendo)'],
        ],
        truco:'Lo vas a ver mucho m\u00e1s en textos t\u00e9cnicos y noticias que en una conversaci\u00f3n. Recon\u00f3celo al leer; para hablar casi nunca lo necesitas.',
      },
      { id:'error', ico:'\u26a0\ufe0f', t:'El error que hay que evitar',
        cuerpo:'El espa\u00f1ol usa el gerundio para la acci\u00f3n en curso: \u00abestoy comiendo\u00bb. El alem\u00e1n <b>no tiene esa construcci\u00f3n</b>, y traducirla con Partizip I suena a extranjero de inmediato.',
        comparativa:[
          ['Estoy comiendo','<s>Ich bin essend</s>','Ich esse <b>gerade</b>. \u2014 o simplemente <b>Ich esse</b>.'],
          ['Estaba trabajando','<s>Ich war arbeitend</s>','Ich habe <b>gerade</b> gearbeitet.'],
          ['El ni\u00f1o est\u00e1 jugando','<s>Das Kind ist spielend</s>','Das Kind spielt <b>gerade</b>.'],
        ],
        aviso:'El alem\u00e1n resuelve el \u00abestar +ndo\u00bb con el presente normal, y si hace falta marcar que es ahora, con <b>gerade</b> o <b>im Moment</b>.',
      },
      { id:'contraste', ico:'\u2696\ufe0f', t:'Los dos, uno al lado del otro',
        cuerpo:'La misma ra\u00edz, dos significados opuestos: quien hace la acci\u00f3n frente a quien la recibe.',
        tabla:{cols:['','Partizip I','Partizip II'], filas:[
          ['Forma','infinitivo + d','ge\u2026t / ge\u2026en'],
          ['Significado','activo, en curso','pasivo o terminado'],
          ['Ejemplo','das <b>kochende</b> Wasser<br><span class=\'pz-mini\'>el agua que hierve</span>','das <b>gekochte</b> Wasser<br><span class=\'pz-mini\'>el agua hervida</span>'],
          ['Otro','der <b>lesende</b> Mann<br><span class=\'pz-mini\'>el hombre que lee</span>','das <b>gelesene</b> Buch<br><span class=\'pz-mini\'>el libro le\u00eddo</span>'],
          ['Se usa para','describir (adjetivo/adverbio)','Perfekt, pasiva y adjetivo'],
        ]},
      },
    ],
  },

  // Las palabras de una sección, y el recuento para pintarlo en la pestaña.
  de: function (cat) {
    return this.voc.filter(function (v) { return v.cat === cat; });
  },
  cuantas: function (cat) { return this.de(cat).length; },
  // La palabra del día: la misma todo el día, distinta cada día, sin guardar nada.
  delDia: function (dia) {
    return this.voc[(dia || 0) % this.voc.length];
  },
};

if (typeof module !== 'undefined' && module.exports) module.exports = ALEMAN_VOCAB;
