/* ════════════════════════════════════════════════════════════════════════════
   AERORESINAS — todo el contenido de la página, en un solo archivo.

   Se separó del HTML el 2026-09-17, cuando Adán pidió "muchísima información":
   con la página completa el texto pasó de 400 a más de 1,500 líneas y editarlo
   dentro del HTML era buscar una aguja. Aquí está TODO lo que se lee en
   pantalla, en los dos idiomas, y el HTML solo lo pinta.

   Tres reglas al escribir aquí:
     1. Lo que se afirma de José Arturo sale de su perfil profesional o de las
        fotos de sus trabajos. Nada inventado: si un dato no está, se marca
        entre [corchetes] y sale señalado en la página.
     2. Lo que se explica de una TÉCNICA (bolsa de vacío, panel sándwich,
        doublers…) es conocimiento aeronáutico estándar, y se escribe para que
        lo entienda el dueño de la aeronave, no el técnico.
     3. Cada caso de la sección "Trabajos" corresponde a fotos reales suyas, en
        el orden en que ocurrió el trabajo.
   ════════════════════════════════════════════════════════════════════════════ */

/* `var`, no `const`: Posts/posts.html carga este archivo y el de Heliescala en la misma
   página, y dos `const PERFIL` en scripts distintos chocan. Con `var` cada uno se guarda en
   su cajón (AERO, HELI) antes de que el siguiente lo pise. Para la web es indistinto. */
var PERFIL = {
  nombre:    'José Arturo Martínez Ponce',
  puesto:    'Técnico de mantenimiento de aeronaves',
  ciudad:    'Miguel Hidalgo, Ciudad de México',
  cobertura: 'México, Panamá y Guatemala',
  anios:     '36',                    // en Airbus, 1988-2024
  desde:     '1988',
  donde:     'Airbus',
  paises:    '3',
  licencia:  'DGAC',
  // Solo dígitos para wa.me (52 = México); `whatsappTxt` es cómo se escribe en pantalla.
  whatsapp:    '525586184919',
  whatsappTxt: '+52 55 8618 4919',
  correo:      'adanarturomartinez@gmail.com',
  // Dos enlaces distintos y los dos importan: el PERSONAL es la prueba de los 36
  // años en Airbus —lo que hace que un operador confíe— y el de EMPRESA es la
  // marca. Por eso salen en filas separadas y con etiqueta propia.
  linkedin:    'https://www.linkedin.com/in/jose-arturo-martinez-ponce-34697b243/',
  linkedinTxt: 'José Arturo Martínez Ponce',
  linkedinEmp:    'https://www.linkedin.com/company/107151473/',
  linkedinEmpTxt: 'Aeroresinas',
};

var T = {
 es: {
  // ── Barra ──────────────────────────────────────────────────────────────
  marcaSub:'REPARACIÓN ESTRUCTURAL DE HELICÓPTEROS',
  otroIdioma:'English',
  nav:[['#reparacion','Qué reparo'],['#trabajos','Trabajos'],['#flota','Aeronaves'],['#metodo','Cómo trabajo'],
       ['#tecnicas','Técnicas'],['#trayectoria','Quién soy'],['#faq','Preguntas']],

  // ── Hero ───────────────────────────────────────────────────────────────
  heroOjo:'Composites · técnicas al vacío · parabrisas',
  heroT1:'Tu helicóptero no viaja al taller.', heroT2:'El taller viaja a tu helicóptero.',
  heroSub:'Reparo estructura en fibra de vidrio, acrílicos y estructuras remachadas, con <b>{anios} años en {donde}</b> detrás. Voy a tu hangar, a campo o a donde quedó la aeronave.',
  ctaDanio:'Mandar fotos del daño', ctaCaso:'Ver trabajos hechos',
  datos:[['{anios}','Años en {donde}'],['{licencia}','Licencia'],['Bell · Airbus · Robinson','Marcas que reparo'],['{paises}','Países atendidos']],
  pieHero:'<b>Evaluando el daño antes de tocar nada.</b> El panel se mide y se compara con el manual: se decide si se repara o se sustituye.',
  pieAntes:'<b>Antes.</b> Composite delaminado en el techo de cabina.',
  pieDespues:'<b>Después.</b> La misma zona, lista para pintura.',

  // ── Qué repara ─────────────────────────────────────────────────────────
  repT:'Qué reparo', repN:'07 SERVICIOS',
  repSub:'Siete trabajos, y los hago completos: evaluación del daño, reparación conforme al manual de la aeronave y entrega documentada con fotos. Si algo excede los límites del manual y hay que sustituir la pieza, te lo digo antes de empezar — no después.',
  servicios:[
   ['estruc','Estructura de fuselaje y cabina','fotos/estructura-piel.jpg',
    'Piel, largueros, cuadernas y refuerzos. Se retira el material dañado hasta llegar a estructura sana, se repone con el mismo calibre y aleación que pide el manual, y se cierra con el patrón de remachado original.',
    'La clave está en lo que no se ve: un daño de 10 cm en la piel puede haber deformado el larguero de abajo. Por eso la zona se abre antes de presupuestar.',
    'Ala rotativa y ala fija'],
   ['fuse','Composites: fibra de vidrio y resina','fotos/composite-fibra.jpg',
    'Delaminaciones, impactos, fisuras y zonas con agua infiltrada. Se sanea hasta fibra firme, se laminan capas nuevas respetando la orientación original y se cura bajo bolsa de vacío.',
    'Un composite no se “rellena”: se reconstruye capa por capa. Si las fibras no van orientadas como las de fábrica, la pieza parece reparada y no lo está.',
    'La especialidad de la casa'],
   ['panel','Panel sándwich y nido de abeja','fotos/panel-1.jpg',
    'Las piezas ligeras del helicóptero —puertas, carenados, techos— son dos pieles finas sobre un núcleo. Cuando entra agua o se aplasta el núcleo, se abre la piel, se sustituye el núcleo dañado y se cierra.',
    'Es el daño que más se subestima: por fuera se ve una abolladura y por dentro el núcleo está húmedo y deshecho. Se detecta golpeando la superficie y oyendo el cambio de sonido.',
    'Núcleo, piel y sellado'],
   ['corro','Corrosión','fotos/corrosion.jpg',
    'Detección, remoción y protección. Se remueve hasta material sano, se mide cuánto espesor quedó y se compara con el límite del manual; después se protege para que no vuelva a arrancar.',
    'La corrosión no se limpia ni se pinta encima. Lo que se ve en la superficie casi nunca es todo: por eso se decapa alrededor hasta ver dónde termina de verdad.',
    'Detección · remoción · protección'],
   ['cristal','Parabrisas, ventanas y acrílicos','fotos/parabrisas.jpg',
    'Cristales agrietados o delaminados, acrílicos con fisuras y marcos que filtran. Cambio completo o reparación cuando el daño y el manual lo permiten, con el sellado y el apriete que corresponde.',
    'Un acrílico se agrieta por tensión, no por golpe: apretarlo de más o montarlo forzado lo parte a las pocas horas de vuelo. El marco importa tanto como el cristal.',
    'Cambio, reparación y sellado'],
   ['remache','Estructuras remachadas y sellado','fotos/tomas.jpg',
    'Sustitución de remaches flojos o vibrantes, refuerzos (doublers), y sellado aeronáutico de juntas, ventanas y pasos de piel.',
    'Un remache que “trabaja” marca la piel alrededor. Se cambia por el siguiente diámetro respetando distancias al borde, y la junta se sella para que no entre humedad.',
    'Remachado · doublers · sellado'],
   ['antena','Antenas, tomas y accesorios','fotos/rejilla-2.jpg',
    'Montaje, desmontaje y reparación de la zona donde va la antena o la toma de aire: refuerzo, sellado y restitución del puenteo eléctrico.',
    'Casi nunca falla la antena: falla la piel donde está montada, que se fatiga por la vibración. Si se monta sin doubler, el agujero se vuelve grieta.',
    'Montaje · refuerzo · bonding'],
  ],

  // ── Trabajos ───────────────────────────────────────────────────────────
  trabT:'Trabajos, paso a paso', trabN:'CASOS REALES',
  trabNum:'TRABAJO', trabDe:'de', trabAnt:'Trabajo anterior', trabSig:'Trabajo siguiente',
  trabSub:'Cada caso es una reparación mía, fotografiada mientras la hacía. No hay imágenes de catálogo aquí: son las etapas reales, en orden, con lo que se hizo en cada una.',
  trabajos:[
   {t:'Techo de cabina · Bell', z:'Composite · bolsa de vacío',
    r:'Daño en el techo de la cabina, sobre la puerta. Se abrió la zona, se retiró todo el material comprometido, se laminaron capas nuevas de fibra y se cerró hasta dejar la superficie lista para pintura. La aeronave salió con el techo sin rastro de la reparación.',
    f:[['fotos/techo-1.jpg','<b>01 · Se abre y se sanea.</b> Todo el material dañado sale hasta llegar a fibra firme. La zona siempre termina siendo más grande de lo que se veía desde fuera.'],
       ['fotos/techo-2.jpg','<b>02 · Enmascarado y laminado.</b> Se protege lo que no se toca y se colocan las capas nuevas, orientadas como las originales.'],
       ['fotos/techo-3.jpg','<b>03 · Relleno y lijado.</b> Se iguala el perfil con la superficie de al lado: la reparación tiene que desaparecer al tacto antes que a la vista.'],
       ['fotos/techo-4.jpg','<b>04 · Terminado.</b> Pintado y montado. Ni la línea de la reparación se distingue.']]},
   {t:'Carenado lateral · núcleo dañado', z:'Panel sándwich · sustitución de núcleo',
    r:'Un carenado con el núcleo deshecho por humedad. Se abrió la piel, se retiró el núcleo dañado, se repuso material nuevo, se cerró la piel y se devolvió la pieza pintada y con sus rejillas montadas.',
    f:[['fotos/panel-1.jpg','<b>01 · Lo que había dentro.</b> Con la piel abierta se ve el núcleo comprometido: por fuera solo se notaba una zona blanda.'],
       ['fotos/panel-2.jpg','<b>02 · Núcleo nuevo y relleno.</b> Se repone el material y se sella el contorno para que no vuelva a entrar humedad.'],
       ['fotos/panel-3.jpg','<b>03 · Lijado y ajuste.</b> La pieza se trabaja hasta recuperar su forma, con la rejilla puesta para comprobar el asiento.'],
       ['fotos/panel-4.jpg','<b>04 · Entregado.</b> Pintado con su librea y listo para montar en la aeronave.']]},
   {t:'Techo de cabina · composite delaminado', z:'Delaminación · laminado manual',
    r:'Delaminación en el techo, sobre la cabina de mando. Se retiró la zona afectada, se laminó fibra nueva y se cerró dejando la superficie preparada para pintura.',
    f:[['fotos/composite-antes.jpg','<b>01 · El daño, abierto.</b> El contorno se marca donde la fibra deja de estar firme, no donde se ve la marca.'],
       ['fotos/composite-fibra.jpg','<b>02 · Fibra nueva.</b> Capas colocadas y curadas sobre la zona saneada.'],
       ['fotos/composite-despues.jpg','<b>03 · Cerrado.</b> Relleno, lijado y superficie lista para pintura.']]},
   {t:'Piel y estructura · sustitución completa', z:'Chapa · remachado',
    r:'Piel retirada para llegar a la estructura. Con los largueros a la vista se comprueba el estado real, se repone la piel con material nuevo y se cierra con su patrón de remachado y su protección anticorrosiva.',
    f:[['fotos/corrosion.jpg','<b>01 · Decapado.</b> Al quitar la pintura aparece toda la corrosión, no solo la que se veía.'],
       ['fotos/estructura-piel.jpg','<b>02 · Estructura a la vista.</b> Con la piel fuera se mide el estado de largueros y refuerzos.'],
       ['fotos/estructura-nueva.jpg','<b>03 · Piel nueva imprimada.</b> Material nuevo, protegido antes de cerrar.']]},
   {t:'Nariz · impactos y acabado', z:'Composite · acabado',
    r:'Nariz con impactos y pintura levantada, de las horas de vuelo. Se saneó, se rellenó y se devolvió la superficie a su perfil original.',
    f:[['fotos/nariz-antes.jpg','<b>01 · Antes.</b> Impactos y pintura levantada a lo largo de toda la nariz.'],
       ['fotos/nariz-despues.jpg','<b>02 · Después.</b> Superficie recuperada y lista para pintura.']]},
   {t:'Parabrisas · marco y montaje', z:'Acrílico · sellado',
    r:'Sustitución de cristal con preparación del marco. El asiento se limpia y se prepara antes de montar: un acrílico montado sobre un marco sucio o deformado se agrieta en pocas horas de vuelo.',
    f:[['fotos/parabrisas.jpg','<b>01 · Marco preparado.</b> Asiento limpio y protegido antes de recibir el cristal.'],
       ['fotos/parabrisas-2.jpg','<b>02 · Ajuste.</b> Se comprueba el asiento en toda la periferia, sin forzar el acrílico.'],
       ['fotos/parabrisas-3.jpg','<b>03 · Sellado.</b> Sellador aeronáutico en la junta para estanqueidad y protección.']]},
   {t:'Tomas de aire y rejillas', z:'Piel · bonding',
    r:'Reparación de la zona de tomas de aire y rejillas: la piel alrededor se fatiga por vibración y por el paso de aire. Se repara, se restituye el puenteo eléctrico y se monta de nuevo.',
    f:[['fotos/rejilla-1.jpg','<b>01 · Rejilla desmontada.</b> Se trabaja el alojamiento, no solo la pieza.'],
       ['fotos/rejilla-2.jpg','<b>02 · Montada.</b> Asiento limpio, sellado y bonding restituido.'],
       ['fotos/tomas.jpg','<b>03 · En la aeronave.</b> Las tomas ya montadas, con la piel enmascarada para el acabado.']]},
   {t:'Techo con corrosión · larguero y piel nueva', z:'Corrosión · chapa · remachado',
    r:'El techo de una aeronave con corrosión repartida por toda la superficie. Se decapó hasta metal sano para ver dónde terminaba de verdad, se abrió el canal central hasta dejar la estructura a la vista, se repuso la piel completa con material nuevo y se cerró con relleno, protección y las antenas montadas otra vez. Es el trabajo más largo de los que hay aquí, y el que mejor explica por qué no se presupuesta por foto.',
    f:[['fotos/techo2-1.jpg','<b>01 · Lo que había bajo la pintura.</b> Decapado, la corrosión aparece en manchas café por todo el techo. Lo que se veía desde fuera era una fracción de esto.'],
       ['fotos/techo2-2.jpg','<b>02 · La estructura, a la vista.</b> Abierto el canal central quedan los refuerzos longitudinales y sus fijaciones. Aquí se decide qué se repone y qué se sustituye.'],
       ['fotos/techo2-3.jpg','<b>03 · Piel nueva.</b> El panel nuevo, ya imprimado, ocupando todo el largo del techo. Del mismo calibre y con el mismo patrón de fijación que el original.'],
       ['fotos/techo2-4.jpg','<b>04 · Relleno y perfil.</b> Se iguala el perfil con la superficie de al lado hasta que la unión no se siente al pasar la mano.'],
       ['fotos/techo2-5.jpg','<b>05 · Cerrado.</b> Superficie protegida y lista para pintura, con las antenas y sus tapas otra vez en su sitio.']]},
   {t:'Radomo · delaminación en el cono de nariz', z:'Composite · sellado',
    r:'El cono de nariz de una aeronave con la piel delaminada en una zona grande. El radomo no es una pieza cualquiera: por debajo va la antena del radar meteorológico, así que el espesor y el material importan tanto como la forma. Se decapó, se midió cuánto había cedido, se saneó hasta fibra firme y se cerró sellado.',
    f:[['fotos/radomo-1.jpg','<b>01 · Decapado por zonas.</b> Se retira pintura en manchas para encontrar el contorno real del daño, que casi nunca coincide con lo que se ve.'],
       ['fotos/radomo-2.jpg','<b>02 · Se mide.</b> Regla sobre la zona abierta: hay que saber cuánto material se perdió antes de decidir si se repara o se sustituye. Al fondo se distingue la huella del núcleo.'],
       ['fotos/radomo-3.jpg','<b>03 · Saneado completo.</b> Toda la zona comprometida fuera, hasta dejar fibra firme en todo el contorno.'],
       ['fotos/radomo-4.jpg','<b>04 · Sellado.</b> La zona reconstruida y sellada, lista para imprimación y pintura.']]},
   {t:'Antenas · desmontaje, sellado y puenteo eléctrico', z:'Antenas · sellado · puenteo',
    r:'Una antena no se atornilla y ya. Se desmonta, se sanea la zona, se repone la base, se sella para que no entre agua y se restituye el <b>puenteo eléctrico</b>: las tiras que conectan la antena a la estructura y le dan camino a la corriente de un rayo. Si falta ese camino, la descarga se lo busca sola.',
    f:[['fotos/antena-1.jpg','<b>01 · Base fuera.</b> Retirada la antena queda el asiento, el agujero del cable y el sellador viejo, que sale entero.'],
       ['fotos/antena-2.jpg','<b>02 · La base y su cable.</b> Asiento nuevo, con el coaxial y su conector, enmascarado para sellar solo lo que toca.'],
       ['fotos/antena-3.jpg','<b>03 · El puenteo.</b> Las tiras de puenteo en estrella alrededor de la base: es lo que conecta la antena con la estructura del avión.'],
       ['fotos/antena-4.jpg','<b>04 · Sellado.</b> El contorno sellado y curado, junto a la tapa de la antena de al lado, ya montada.'],
       ['fotos/antena-5.jpg','<b>05 · En la aeronave.</b> Las dos antenas montadas sobre el fuselaje pintado, con su cable de puenteo a la vista entre las dos.']]},
   {t:'Costado bajo el parabrisas · de principio a fin', z:'Composite · bolsa de vacío',
    r:'El caso más completo de la página. El panel del costado, justo bajo el parabrisas, se abrió por completo: se ve el daño, la piel desprendida, la preparación, el laminado, el curado bajo bolsa de vacío y la pieza terminada. Seis etapas de la misma reparación, en el orden en que ocurrió.',
    f:[['fotos/costado-1.jpg','<b>01 · El daño.</b> El panel abierto, con el interior de la cabina a la vista. Así llegó la aeronave.'],
       ['fotos/costado-2.jpg','<b>02 · La piel desprendida.</b> Se sostiene contra su sitio para comprobar cuánto se puede recuperar y dónde está el límite del manual. El número de parte sigue legible en el metal.'],
       ['fotos/costado-3.jpg','<b>03 · Preparado.</b> La zona saneada e imprimada, con el contorno enmascarado para que el material nuevo pegue solo donde debe.'],
       ['fotos/costado-4.jpg','<b>04 · Laminado.</b> Capas nuevas colocadas y curadas, respetando la orientación de las fibras originales.'],
       ['fotos/costado-5.jpg','<b>05 · Bolsa de vacío.</b> La bolsa sellada sobre la reparación y la manguera conectada: el vacío aprieta las capas contra la pieza mientras cura y saca el aire atrapado.'],
       ['fotos/costado-6.jpg','<b>06 · Terminado.</b> Relleno, lijado y con la curva del fuselaje recuperada. Lista para pintura.']]},
   {t:'Nariz del monomotor · panel roto', z:'Composite · laminado',
    r:'Una aeronave monomotor que llegó con el panel de la nariz roto y la estructura de dentro expuesta. Se reconstruyó laminando, se igualó con el resto de la superficie y se devolvió pintada con su librea.',
    f:[['fotos/nariz2-1.jpg','<b>01 · Como llegó.</b> El panel roto, con el interior a la vista y las grietas saliendo del impacto.'],
       ['fotos/nariz2-2.jpg','<b>02 · Reconstruido.</b> Capas nuevas curadas sobre la zona saneada, con el contorno enmascarado.'],
       ['fotos/nariz2-3.jpg','<b>03 · Junto al faro.</b> Otra zona de la misma nariz, con el material nuevo puesto y el borde sellado para que no entre agua por la junta.'],
       ['fotos/nariz2-4.jpg','<b>04 · Entregada.</b> La nariz terminada, con la librea completa. No queda rastro de por dónde iba la rotura.']]},
   {t:'Estabilizador horizontal · borde y núcleo', z:'Panel sándwich · composite',
    r:'El estabilizador horizontal es una superficie de vuelo, y ahí no se improvisa: si el perfil cambia, cambia cómo vuela la aeronave. Se abrió el extremo hasta ver el núcleo, se repuso material y se cerró respetando la forma original, con la librea pintada encima.',
    f:[['fotos/estab2-1.jpg','<b>01 · El extremo abierto.</b> Con la piel retirada aparece el núcleo verde del panel sándwich: dos pieles finas y un relleno ligero entre ellas.'],
       ['fotos/estab2-2.jpg','<b>02 · El corte, de cerca.</b> Se ve el espesor real de la pieza y hasta dónde llega el núcleo sano. Ese borde es el que marca hasta dónde se sanea.'],
       ['fotos/estab2-3.jpg','<b>03 · Con su librea.</b> La pieza cerrada y pintada, con las franjas que llevaba y sus fijaciones en su sitio.']]},
   {t:'Puertas y estabilizador', z:'Estructura · composite',
    r:'Reparación de puertas y de superficies de cola: son las piezas que más se golpean en tierra y las que más pesan en el aspecto general de la aeronave.',
    f:[['fotos/puerta.jpg','<b>01 · Puerta.</b> Zona abierta y saneada antes de reponer material.'],
       ['fotos/estabilizador.jpg','<b>02 · Estabilizador.</b> Borde de ataque con la fibra a la vista, listo para laminar.']]},
  ],

  // ── Método ─────────────────────────────────────────────────────────────
  metT:'Cómo trabajo', metN:'EL MÉTODO',
  metSub:'Sin taller fijo, sin lista de espera y sin mover la aeronave. Seis pasos, y el primero es una foto por WhatsApp.',
  pasos:[
   ['Mándame fotos del daño','El área de cerca y de lejos, y si lo tienes a mano el número de parte o la página del manual. Con eso ya te puedo decir si es reparable o si va a sustitución.'],
   ['Evaluación y presupuesto','Te digo qué se repara, qué hay que sustituir, cuánto tiempo toma y qué cuesta. La evaluación no te la cobro.'],
   ['Voy a donde está la aeronave','Llego a tu hangar con herramienta y material. No hay que trasladar la aeronave ni esperar un espacio en un taller.'],
   ['Se abre y se mide','El daño se delimita de verdad: se retira material hasta llegar a zona sana y se compara con los límites del manual. Aquí es donde un presupuesto serio se distingue de uno hecho por foto.'],
   ['Reparación y curado','Laminado, remachado, sellado o sustitución, según el caso, con los tiempos de curado que pide el material. Las prisas aquí se pagan en vuelo.'],
   ['Entrega con reporte','La reparación documentada con fotos del antes, el proceso y el después, para tu bitácora.'],
  ],
  cobT:'Cobertura:', cobD:'He trabajado para operadores civiles, privados y gubernamentales de los tres países, en hangar y en campo. Para salidas fuera de mi base acordamos traslado y estancia antes de viajar.',
  aogT:'Aeronave en tierra (AOG)',
  aogD:'Si tienes una aeronave detenida esperando una reparación estructural, esa es exactamente la llamada que atiendo primero. Soporte AOG con movilidad internacional: viajo en cuanto se confirme.',
  aogCta:'Llamar por un AOG',

  // ── Técnicas ───────────────────────────────────────────────────────────
  tecT:'Las técnicas, explicadas', tecN:'PARA ENTENDER EL PRESUPUESTO',
  tecSub:'Si nunca has mandado reparar una estructura, estas ocho palabras son las que vas a oír. Aquí están en claro, para que puedas juzgar un presupuesto en vez de aceptarlo.',
  tecnicas:[
   ['Bolsa de vacío (vacuum bagging)','Se cubre el laminado con una bolsa y se le hace el vacío mientras cura. La presión compacta las capas, saca el aire y el exceso de resina, y deja la proporción fibra-resina correcta. <b>Sin vacío el laminado queda poroso</b>: se ve igual y aguanta menos.'],
   ['SRM, AMM y Boletines','El <b>SRM</b> es el manual de reparaciones estructurales del fabricante: dice hasta qué tamaño de daño se repara y cómo. El <b>AMM</b> es el de mantenimiento. Un <b>Boletín de Servicio</b> es una instrucción posterior del fabricante. Una reparación que no se apoya en uno de los tres no es una reparación aeronáutica.'],
   ['Panel sándwich y nido de abeja','Dos pieles finas pegadas a un núcleo en forma de panal. Es rígido y pesa poquísimo, pero si entra agua el núcleo se degrada y la pieza pierde resistencia <b>sin que se note por fuera</b>. Se comprueba golpeando la superficie: el sonido cambia donde está despegado.'],
   ['Doubler (refuerzo)','Una placa que se añade para repartir la carga alrededor de un agujero o una reparación — por ejemplo donde se monta una antena. Sin doubler, el borde del agujero concentra el esfuerzo y termina en grieta.'],
   ['Delaminación','Las capas de un composite se separan entre sí, normalmente por un impacto. Puede no verse nada en la superficie y estar despegado por dentro; por eso se busca por sonido y se abre hasta encontrar fibra firme.'],
   ['Líquidos penetrantes','Ensayo no destructivo: se aplica un líquido coloreado que entra en las grietas y luego un revelador que las saca a la vista. Sirve para encontrar fisuras que el ojo no ve en piezas metálicas.'],
   ['Puenteo eléctrico (bonding)','Las partes de la aeronave tienen que estar eléctricamente unidas para conducir una descarga atmosférica y para que no se acumule estática. Cada vez que se quita y se pone una pieza —una antena, una rejilla— hay que <b>restituir esa continuidad</b>.'],
   ['Sellado aeronáutico','No es silicón: son compuestos específicos que sellan juntas, ventanas y pasos de piel, resisten combustible y temperatura, y sobre todo <b>evitan que entre humedad</b>, que es de donde nace la corrosión.'],
  ],

  // ── Trayectoria y quién es ─────────────────────────────────────────────
  trayT:'36 años dentro de una aeronave', trayN:'TRAYECTORIA',
  traySub:'No empecé ayer ni aprendí por mi cuenta: soy técnico de mantenimiento de aeronaves formado y curtido en <b>Airbus</b>, desde 1988. Lo que hoy hago por mi cuenta es lo mismo que hice durante 36 años en una línea de producción, con sus manuales y sus boletines.',
  trayectoria:[
   ['1988 — 2024','Airbus · Técnico de mantenimiento','<b>36 años de planta</b>, trabajando estructura en flotas A320, A321, ATR 42 y ATR 72: inspección estructural, reparación de chapa, composites y modificaciones conforme a <b>SRM, AMM y Boletines de Servicio</b>. Reparaciones permanentes y temporales, con la integridad estructural y la aeronavegabilidad documentadas.', false],
   ['2025 — hoy','Aeroresinas · Por mi cuenta','Reparación estructural de <b>helicópteros</b>: fibra de vidrio, técnicas al vacío, acrílicos y estructuras remachadas. Para operadores civiles, privados y gubernamentales en <b>México, Panamá y Guatemala</b>, en hangar o en campo — incluido el <b>soporte AOG</b> con la aeronave en tierra.', true],
  ],
  capT:'Lo que he reparado, con ese nombre',
  capacidades:['Radomos','Piel de fuselaje','Botas antihielo','Reparación interior de cubiertas','Sustitución de piel','Boletines de servicio','Instalación de antenas','Reparación de puertas','Remoción de corrosión','Modificación de winglets','Inspección con líquidos penetrantes','Panel sándwich de nido de abeja','Refuerzos (doublers) para antenas','Cambio de remaches vibrantes','Reparación al vacío (vacuum bag)','Compuestos de sellado','Restitución del puenteo eléctrico','Montaje y retiro de insertos','Composites monolíticos y sándwich','Estabilizador horizontal'],
  capP:'Veinte trabajos distintos, de su historial en Airbus. Los de estructura y composite son exactamente los que hoy aplica a un helicóptero: <b>la técnica es la misma, cambia la aeronave</b>.',
  pieRetrato:'<b>Soy José Arturo Martínez Ponce.</b> Licencia {licencia}, {anios} años en {donde} y hoy en tu hangar.',
  quienT:'Quién soy',
  quienD:'Soy <b>{nombre}</b>, técnico de mantenimiento de aeronaves con licencia <b>{licencia}</b>, especialista en composites, técnicas al vacío y parabrisas.<br><br>Entré a <b>Airbus en 1988</b> y estuve <b>36 años</b> en estructura: A320, A321, ATR 42 y ATR 72. Radomos, piel de fuselaje, paneles de nido de abeja, corrosión, modificación de winglets, instalación de antenas con sus refuerzos, reparación al vacío, sellado, puenteo eléctrico. Todo conforme a SRM, AMM y boletines, y todo documentado: en una línea de producción una reparación no existe si no está escrita.<br><br>Desde <b>2025 trabajo por mi cuenta</b>, y lo hago en helicópteros: Bell, Airbus Helicopters y Robinson, para operadores civiles, privados y gubernamentales de <b>México, Panamá y Guatemala</b>. En hangar cuando se puede y en campo cuando toca, porque una aeronave detenida cuesta dinero cada día.<br><br>Estoy disponible para <b>proyectos por contrato, soporte urgente (AOG) y colaboración con talleres MRO</b>. Y contesto yo: no hay conmutador ni intermediario entre tu aeronave y quien la va a reparar.',
  credT:'Lo que respalda el trabajo',
  credenciales:[
   ['Licencia {licencia}','Técnico de mantenimiento de aeronaves con licencia de la autoridad aeronáutica.'],
   ['36 años en Airbus','1988 a 2024, estructura en A320, A321, ATR 42 y ATR 72.'],
   ['Reparaciones conforme a manual','SRM, AMM y Boletines de Servicio — permanentes y temporales, con la aeronavegabilidad documentada.'],
   ['Bell · Airbus Helicopters · Robinson','Operadores civiles, privados y gubernamentales.'],
   ['México, Panamá y Guatemala','En hangar y en campo, con movilidad internacional.'],
   ['Soporte AOG y talleres MRO','Proyectos por contrato, soporte urgente y colaboración con talleres.'],
  ],

  // ── Aeronaves terminadas ───────────────────────────────────────────────
  // Lo único de la página que NO es trabajo abierto. Un dueño de aeronave ve
  // paneles rotos en todas las secciones anteriores; aquí ve el resultado.
  floT:'Las aeronaves con las que trabajo', floN:'EN EL HANGAR',
  floSub:'Bimotores corporativos, monomotores de trabajo aéreo, ambulancias aéreas y aeronaves de operadores de fuera de México. Estas son del tipo y del tamaño que entran al hangar donde reparo — completas, montadas y en línea de vuelo.',
  flota:[
   ['fotos/real-h145.jpg','<b>Bimotor corporativo Airbus.</b> Cinco palas, fenestrón y librea azul sobre blanco. Matrícula mexicana.'],
   ['fotos/real-sgm.jpg','<b>Monomotor de trabajo aéreo.</b> Librea roja y blanca de un operador institucional, con patines altos.'],
   ['fotos/real-panama.jpg','<b>Ambulancia aérea, matrícula HP.</b> El prefijo HP es de Panamá: así se ven los trabajos que salen del país.'],
   ['fotos/real-fenestron.jpg','<b>Deriva y fenestrón.</b> El rotor de cola va dentro de la deriva. Esa pieza es composite puro, y es de las que más trabajo dan.'],
   ['fotos/real-h125.jpg','<b>Cola de un H125.</b> La designación y el número de serie, pintados en la deriva.'],
   ['fotos/real-h145b.jpg','<b>El mismo bimotor, de perfil.</b> Con la aeronave así de limpia no se adivina qué paneles estuvieron abiertos.'],
  ],

  // ── Galería ────────────────────────────────────────────────────────────
  galT:'Más del taller', galN:'GALERÍA',
  galSub:'Lo que no cabe en un caso: el hangar, el taller montado alrededor de la aeronave, las bolsas de vacío curando, la cabina protegida y las piezas pequeñas que también se reparan.',
  galeria:[
   ['fotos/hangar.jpg','<b>El hangar.</b> Se trabaja donde está la aeronave: no hay que moverla.'],
   ['fotos/trabajando.jpg','<b>En campo.</b> Sellando el marco de una ventanilla, con la aeronave montada.'],
   ['fotos/taller-1.jpg','<b>Aeronave abierta.</b> Puertas fuera, interior desmontado y la mesa de trabajo al lado, con la aspiración conectada.'],
   ['fotos/taller-2.jpg','<b>Sobre caballetes.</b> Fuselaje sin tren, apoyado para poder llegar a la panza y a los costados.'],
   ['fotos/vacio-1.jpg','<b>Bolsa de vacío y lámpara.</b> La bolsa sellada sobre la zona y la lámpara dando calor: así cura un composite como pide el manual.'],
   ['fotos/vacio-2.jpg','<b>Curando bajo la panza.</b> La misma reparación desde abajo, con la bolsa puesta y el trabajo en marcha.'],
   ['fotos/cabina.jpg','<b>Cabina protegida.</b> Antes de tocar nada se cubren asientos e instrumentos. El polvo de lijado se mete en todo.'],
   ['fotos/bahia.jpg','<b>Bahía de equipo.</b> Batería, aviónica y conductos. Para llegar a la piel hay que desmontar lo que va encima, y volver a montarlo igual.'],
   ['fotos/circular.jpg','<b>Reparación pequeña.</b> Una zona de pocos centímetros junto a la ventanilla: no todo es un panel completo.'],
   ['fotos/louver.jpg','<b>Rejilla y condensador.</b> Detrás de la rejilla va el condensador del aire acondicionado, que también se desmonta para trabajar.'],
   ['fotos/fuselaje.jpg','<b>Aeronave desmontada.</b> Para llegar a la piel hay que quitar lo que va encima.'],
   ['fotos/borde-ataque.jpg','<b>Borde de ataque abierto.</b> La fibra a la vista, lista para reponer material.'],
  ],

  // ── Preguntas ──────────────────────────────────────────────────────────
  faqT:'Lo que suelen preguntar', faqN:'PREGUNTAS',
  faq:[
   ['¿Puede repararse o hay que cambiar la pieza?','Depende del tamaño del daño y de dónde esté, y eso lo fija el manual de tu aeronave, no el criterio de nadie. Por eso la zona se abre y se mide antes de dar un precio definitivo: un presupuesto hecho solo por foto es una estimación.'],
   ['¿Cuánto tarda?','Un composite pequeño puede quedar en uno o dos días; una sustitución de piel con estructura debajo lleva más, y el curado tiene sus tiempos y no se acortan. La estimación te la da con el presupuesto, antes de empezar.'],
   ['¿Tengo que llevar la aeronave a algún lado?','No. Voy yo a donde esté: tu hangar, la base o donde quedó — es la razón de ser de este servicio, y por eso no hay taller a donde mandarla. La excepción son las <b>piezas pequeñas desmontadas</b>: una tapa, un carenado, una ventanilla o un acrílico sí me los puedes entregar, los reparo y te los devuelvo listos para montar.'],
   ['¿Trabajas fuera de la Ciudad de México?','Sí. He trabajado en México, Panamá y Guatemala. Para salidas acordamos traslado y estancia antes de viajar, y para una aeronave en tierra salgo en cuanto se confirme.'],
   ['¿Qué necesitas para cotizar?','Fotos del área de cerca y de lejos, el modelo y la matrícula, y si lo tienes a mano el número de parte o la página del manual. Con eso alcanza para una primera respuesta.'],
   ['¿Qué entregas al terminar?','La aeronave reparada y un reporte con fotos del antes, el proceso y el después, para que quede en tu bitácora.'],
   ['¿Trabajas con talleres MRO?','Sí, y es parte de lo que ofrezco: colaboración con talleres para trabajos de estructura y composite, por contrato o por proyecto.'],
   ['¿Y si el daño excede el manual?','Te lo digo y no se repara: se sustituye. Preferir un remiendo que no ampara el manual es exactamente lo que no se hace aquí.'],
  ],

  // ── Contacto ───────────────────────────────────────────────────────────
  conT:'Cuéntame qué le pasó a tu aeronave',
  conSub:'Con una foto y dos líneas te digo si tiene arreglo y cuánto cuesta. Contesto yo, no un conmutador.',
  visorAyuda:'CLIC EN LA FOTO PARA VERLA A TAMAÑO REAL · ← → PARA PASAR',
  kWa:'WHATSAPP', kMail:'CORREO', kIn:'LINKEDIN', kEmp:'EMPRESA', kBase:'BASE', kLic:'LICENCIA',
  formT:'Mándale el caso', fNombre:'NOMBRE', fAeronave:'AERONAVE', fQue:'QUÉ PASÓ',
  phNombre:'Cómo te llamas', phAeronave:'Modelo y matrícula — ej. Bell 407, XA-XXX', phQue:'Dos líneas: dónde está el daño y desde cuándo',
  formNota:'Se abre WhatsApp con el mensaje ya escrito. Después me mandas las fotos por ahí mismo.',
  formBtn:'Enviar por WhatsApp',
  waSaludo:'Hola, vi la página de Aeroresinas.',
  waNombre:'Soy', waAeronave:'Aeronave', waQue:'Lo que pasó',
  waAog:'Hola, tengo una aeronave en tierra (AOG) y necesito reparación estructural.',
 },

 en: {
  marcaSub:'HELICOPTER STRUCTURAL REPAIR',
  otroIdioma:'Español',
  nav:[['#reparacion','Services'],['#trabajos','Jobs'],['#flota','Aircraft'],['#metodo','How it works'],
       ['#tecnicas','Techniques'],['#trayectoria','Who I am'],['#faq','FAQ']],

  heroOjo:'Composites · vacuum techniques · windshields',
  heroT1:'Your helicopter does not travel to a shop.', heroT2:'The shop travels to your helicopter.',
  heroSub:'I repair structure in fibreglass, acrylics and riveted structures, with <b>{anios} years at {donde}</b> behind me. I come to your hangar, to the field, or to wherever the aircraft is.',
  ctaDanio:'Send photos of the damage', ctaCaso:'See finished jobs',
  datos:[['{anios}','Years at {donde}'],['{licencia}','License'],['Bell · Airbus · Robinson','Makes I repair'],['{paises}','Countries served']],
  pieHero:'<b>Assessing the damage before touching anything.</b> The panel is measured against the manual: repair or replace.',
  pieAntes:'<b>Before.</b> Delaminated composite on the cabin roof.',
  pieDespues:'<b>After.</b> The same area, ready for paint.',

  repT:'What I repair', repN:'07 SERVICES',
  repSub:'Seven jobs, and I do them end to end: damage assessment, repair per the aircraft manual and a documented handover with photos. If something exceeds the manual limits and the part has to be replaced, I tell you before starting — not after.',
  servicios:[
   ['estruc','Fuselage and cabin structure','fotos/estructura-piel.jpg',
    'Skin, stringers, frames and reinforcements. Damaged material is removed down to sound structure, replaced in the gauge and alloy the manual calls for, and closed with the original rivet pattern.',
    'The key is what you cannot see: a 10 cm skin dent may have deformed the stringer underneath. That is why the area is opened before quoting.',
    'Rotary and fixed wing'],
   ['fuse','Composites: fibreglass and resin','fotos/composite-fibra.jpg',
    'Delaminations, impacts, cracks and water ingress. Cleaned back to firm fibre, new plies laid respecting the original orientation, cured under a vacuum bag.',
    'A composite is not “filled in”: it is rebuilt ply by ply. If the fibres are not oriented like the factory ones, the part looks repaired and is not.',
    'The house specialty'],
   ['panel','Sandwich and honeycomb panels','fotos/panel-1.jpg',
    'The light parts of a helicopter — doors, fairings, roofs — are two thin skins over a core. When water gets in or the core is crushed, the skin is opened, the damaged core replaced, and the skin closed again.',
    'It is the most underestimated damage: outside you see a dent, inside the core is wet and gone. It is found by tapping the surface and listening to the change in sound.',
    'Core, skin and sealing'],
   ['corro','Corrosion','fotos/corrosion.jpg',
    'Detection, removal and protection. Removed down to sound material, remaining thickness measured against the manual limit, then protected so it does not start again.',
    'Corrosion is not cleaned off or painted over. What shows on the surface is rarely all of it: that is why the area around it is stripped until you see where it really ends.',
    'Detection · removal · protection'],
   ['cristal','Windshields, windows and acrylics','fotos/parabrisas.jpg',
    'Cracked or delaminated glass, crazed acrylics and leaking frames. Full replacement or repair when damage and manual allow, with the right sealing and torque.',
    'Acrylic cracks from stress, not impact: overtightened or forced into place, it splits within a few flight hours. The frame matters as much as the pane.',
    'Replacement, repair and sealing'],
   ['remache','Riveted structures and sealing','fotos/tomas.jpg',
    'Replacement of loose or working rivets, doublers, and aviation sealing of joints, windows and skin transitions.',
    'A rivet that “works” marks the skin around it. It is replaced with the next diameter respecting edge distances, and the joint is sealed so moisture stays out.',
    'Riveting · doublers · sealing'],
   ['antena','Antennas, air intakes and accessories','fotos/rejilla-2.jpg',
    'Installation, removal and repair of the area the antenna or intake sits on: reinforcement, sealing and electrical bonding restoration.',
    'The antenna almost never fails: the skin it is mounted on does, fatigued by vibration. Mounted without a doubler, the hole becomes a crack.',
    'Mounting · reinforcement · bonding'],
  ],

  trabT:'Jobs, step by step', trabN:'REAL CASES',
  trabNum:'JOB', trabDe:'of', trabAnt:'Previous job', trabSig:'Next job',
  trabSub:'Every case is a repair of mine, shot while I was doing it. No stock images here: these are the real stages, in order, with what was done at each one.',
  trabajos:[
   {t:'Cabin roof · Bell', z:'Composite · vacuum bag',
    r:'Damage to the cabin roof, above the door. The area was opened, all compromised material removed, new plies of fibre laid, and the surface closed and prepared for paint. The aircraft left with no trace of the repair.',
    f:[['fotos/techo-1.jpg','<b>01 · Opened and cleaned back.</b> All damaged material comes out down to firm fibre. The area always ends up bigger than it looked.'],
       ['fotos/techo-2.jpg','<b>02 · Masked and laid up.</b> Everything untouched is protected and the new plies go on, oriented like the originals.'],
       ['fotos/techo-3.jpg','<b>03 · Filled and sanded.</b> The profile is matched to the surface next to it: the repair has to disappear to the touch before it does to the eye.'],
       ['fotos/techo-4.jpg','<b>04 · Finished.</b> Painted and refitted. Not even the outline shows.']]},
   {t:'Side fairing · damaged core', z:'Sandwich panel · core replacement',
    r:'A fairing with its core destroyed by moisture. The skin was opened, the damaged core removed and replaced, the skin closed, and the part returned painted and with its grilles fitted.',
    f:[['fotos/panel-1.jpg','<b>01 · What was inside.</b> With the skin open the compromised core shows: from outside it was only a soft spot.'],
       ['fotos/panel-2.jpg','<b>02 · New core and filler.</b> Material replaced and the perimeter sealed so moisture cannot get back in.'],
       ['fotos/panel-3.jpg','<b>03 · Sanded and fitted.</b> Worked back to shape, with the grille in place to check the seat.'],
       ['fotos/panel-4.jpg','<b>04 · Delivered.</b> Painted in its livery and ready to fit.']]},
   {t:'Cabin roof · delaminated composite', z:'Delamination · hand lay-up',
    r:'Delamination on the roof, above the flight deck. The affected area was removed, new fibre laid, and the surface closed and prepared for paint.',
    f:[['fotos/composite-antes.jpg','<b>01 · The damage, opened.</b> The outline is marked where the fibre stops being firm, not where the mark shows.'],
       ['fotos/composite-fibra.jpg','<b>02 · New fibre.</b> Plies laid and cured over the cleaned-up area.'],
       ['fotos/composite-despues.jpg','<b>03 · Closed.</b> Filled, sanded and ready for paint.']]},
   {t:'Skin and structure · full replacement', z:'Sheet metal · riveting',
    r:'Skin removed to reach the structure. With the stringers exposed the real condition is checked, new skin is fitted, and it is closed with its rivet pattern and corrosion protection.',
    f:[['fotos/corrosion.jpg','<b>01 · Stripped.</b> With the paint off, all the corrosion shows, not just what was visible.'],
       ['fotos/estructura-piel.jpg','<b>02 · Structure exposed.</b> With the skin off, stringers and reinforcements are measured.'],
       ['fotos/estructura-nueva.jpg','<b>03 · New skin, primed.</b> New material, protected before closing.']]},
   {t:'Nose · impacts and finish', z:'Composite · finishing',
    r:'Nose with impact marks and lifted paint from flight hours. Cleaned back, filled and returned to its original profile.',
    f:[['fotos/nariz-antes.jpg','<b>01 · Before.</b> Impacts and lifted paint along the whole nose.'],
       ['fotos/nariz-despues.jpg','<b>02 · After.</b> Surface recovered and ready for paint.']]},
   {t:'Windshield · frame and fitting', z:'Acrylic · sealing',
    r:'Glass replacement with frame preparation. The seat is cleaned and prepared before fitting: an acrylic mounted on a dirty or distorted frame cracks within a few flight hours.',
    f:[['fotos/parabrisas.jpg','<b>01 · Frame prepared.</b> Seat cleaned and protected before receiving the pane.'],
       ['fotos/parabrisas-2.jpg','<b>02 · Fitting.</b> The seat is checked all the way around, without forcing the acrylic.'],
       ['fotos/parabrisas-3.jpg','<b>03 · Sealing.</b> Aviation sealant in the joint for watertightness and protection.']]},
   {t:'Air intakes and grilles', z:'Skin · bonding',
    r:'Repair of the intake and grille area: the skin around it fatigues from vibration and airflow. It is repaired, electrical bonding is restored, and it is refitted.',
    f:[['fotos/rejilla-1.jpg','<b>01 · Grille removed.</b> The housing is worked, not just the part.'],
       ['fotos/rejilla-2.jpg','<b>02 · Refitted.</b> Clean seat, sealed, bonding restored.'],
       ['fotos/tomas.jpg','<b>03 · On the aircraft.</b> Intakes fitted, skin masked for finishing.']]},
   {t:'Corroded roof · new stringer and skin', z:'Corrosion · sheet metal · riveting',
    r:'An aircraft roof with corrosion spread across the whole surface. It was stripped back to sound metal to find where it really ended, the centre channel was opened until the structure was exposed, the full skin was replaced with new material and it was closed up with filler, protection and the antennas back on. It is the longest job here, and the one that best explains why nothing gets quoted from a photo.',
    f:[['fotos/techo2-1.jpg','<b>01 · What was under the paint.</b> Stripped back, the corrosion shows as brown patches all over the roof. What could be seen from outside was a fraction of this.'],
       ['fotos/techo2-2.jpg','<b>02 · Structure exposed.</b> With the centre channel open, the longitudinal reinforcements and their fixings are visible. This is where it is decided what is repaired and what is replaced.'],
       ['fotos/techo2-3.jpg','<b>03 · New skin.</b> The new panel, already primed, running the full length of the roof — same gauge and the same fastener pattern as the original.'],
       ['fotos/techo2-4.jpg','<b>04 · Filler and profile.</b> The profile is matched to the surface beside it until the joint cannot be felt by hand.'],
       ['fotos/techo2-5.jpg','<b>05 · Closed.</b> Surface protected and ready for paint, with the antennas and their covers back in place.']]},
   {t:'Radome · delamination in the nose cone', z:'Composite · sealing',
    r:'The nose cone of an aircraft with the skin delaminated over a large area. A radome is not just any part: the weather radar antenna sits behind it, so thickness and material matter as much as shape. It was stripped, measured for how much had gone, cleaned back to sound fibre and closed up sealed.',
    f:[['fotos/radomo-1.jpg','<b>01 · Stripped in patches.</b> Paint comes off in patches to find the real edge of the damage, which almost never matches what you can see.'],
       ['fotos/radomo-2.jpg','<b>02 · Measured.</b> A rule across the open area: you have to know how much material was lost before deciding repair or replace. The core imprint is visible behind it.'],
       ['fotos/radomo-3.jpg','<b>03 · Fully cleaned back.</b> Every compromised area out, down to sound fibre all the way round.'],
       ['fotos/radomo-4.jpg','<b>04 · Sealed.</b> The rebuilt area sealed and ready for primer and paint.']]},
   {t:'Antennas · removal, sealing and bonding', z:'Antennas · sealing · bonding',
    r:'An antenna is not bolted on and forgotten. It comes off, the area is cleaned back, the base is replaced, it is sealed so water cannot get in, and the <b>electrical bonding</b> is restored: the straps that connect the antenna to the structure and give a lightning strike somewhere to go. Without that path, the discharge finds its own.',
    f:[['fotos/antena-1.jpg','<b>01 · Base off.</b> With the antenna removed you are left with the seat, the cable hole and the old sealant, which comes out in one piece.'],
       ['fotos/antena-2.jpg','<b>02 · The base and its cable.</b> New seat with the coax and its connector, masked so only what should be sealed is sealed.'],
       ['fotos/antena-3.jpg','<b>03 · The bonding.</b> Bonding straps in a star around the base: this is what ties the antenna to the aircraft structure.'],
       ['fotos/antena-4.jpg','<b>04 · Sealed.</b> The edge sealed and cured, next to the neighbouring antenna cover, already fitted.'],
       ['fotos/antena-5.jpg','<b>05 · On the aircraft.</b> Both antennas fitted on the painted fuselage, with the bonding lead visible between them.']]},
   {t:'Side panel under the windscreen · start to finish', z:'Composite · vacuum bag',
    r:'The most complete case on this page. The side panel, right under the windscreen, was opened completely: the damage, the loose skin, the preparation, the lay-up, the cure under vacuum bag and the finished part. Six stages of the same repair, in the order they happened.',
    f:[['fotos/costado-1.jpg','<b>01 · The damage.</b> The panel torn open, cabin interior visible. This is how the aircraft arrived.'],
       ['fotos/costado-2.jpg','<b>02 · The loose skin.</b> Held back in place to check how much can be saved and where the manual draws the line. The part number is still legible in the metal.'],
       ['fotos/costado-3.jpg','<b>03 · Prepared.</b> The area cleaned back and primed, edge masked so the new material bonds only where it should.'],
       ['fotos/costado-4.jpg','<b>04 · Laid up.</b> New plies placed and cured, following the orientation of the original fibres.'],
       ['fotos/costado-5.jpg','<b>05 · Vacuum bag.</b> The bag sealed over the repair and the hose connected: vacuum presses the plies onto the part while it cures and pulls the trapped air out.'],
       ['fotos/costado-6.jpg','<b>06 · Finished.</b> Filled, sanded and with the fuselage curve back. Ready for paint.']]},
   {t:'Single-engine nose · broken panel', z:'Composite · lay-up',
    r:'A single-engine aircraft that came in with the nose panel broken and the structure behind it exposed. It was rebuilt by laying up, blended into the rest of the surface and handed back painted in its livery.',
    f:[['fotos/nariz2-1.jpg','<b>01 · As it arrived.</b> The broken panel, inside visible, with cracks running out from the impact.'],
       ['fotos/nariz2-2.jpg','<b>02 · Rebuilt.</b> New plies cured over the cleaned-back area, edge masked.'],
       ['fotos/nariz2-3.jpg','<b>03 · By the landing light.</b> Another area of the same nose, new material in and the edge sealed so water cannot get in through the joint.'],
       ['fotos/nariz2-4.jpg','<b>04 · Delivered.</b> The nose finished, full livery on. No trace of where the break ran.']]},
   {t:'Horizontal stabiliser · edge and core', z:'Sandwich panel · composite',
    r:'The horizontal stabiliser is a flying surface, and nothing gets improvised there: change the profile and you change how the aircraft flies. The tip was opened until the core was visible, material was replaced and it was closed respecting the original shape, with the livery painted back on.',
    f:[['fotos/estab2-1.jpg','<b>01 · The tip, open.</b> With the skin off, the green core of the sandwich panel appears: two thin skins with a light filling between them.'],
       ['fotos/estab2-2.jpg','<b>02 · The cut, close up.</b> You can see the real thickness of the part and how far the sound core reaches. That edge is what sets how far back you clean.'],
       ['fotos/estab2-3.jpg','<b>03 · In its livery.</b> The part closed and painted, with the stripes it carried and its fixings back in place.']]},
   {t:'Doors and stabiliser', z:'Structure · composite',
    r:'Repair of doors and tail surfaces: the parts most often knocked on the ground, and the ones that weigh most on how the aircraft looks.',
    f:[['fotos/puerta.jpg','<b>01 · Door.</b> Area opened and cleaned back before replacing material.'],
       ['fotos/estabilizador.jpg','<b>02 · Stabiliser.</b> Leading edge with the fibre exposed, ready to lay up.']]},
  ],

  metT:'How I work', metN:'THE METHOD',
  metSub:'No fixed shop, no waiting list and no moving the aircraft. Six steps, and the first one is a photo over WhatsApp.',
  pasos:[
   ['Send me photos of the damage','The area close up and from a distance, plus the part number or manual page if you have it. That is enough for me to say whether it is repairable or goes to replacement.'],
   ['Assessment and quote','I tell you what can be repaired, what has to be replaced, how long it takes and what it costs. I do not charge for the assessment.'],
   ['I go to the aircraft','I arrive at your hangar with tools and material. No need to move the aircraft or wait for a slot at a shop.'],
   ['Opened and measured','The damage is properly bounded: material is removed down to a sound area and compared with the manual limits. This is where a serious quote differs from one made off a photo.'],
   ['Repair and cure','Lay-up, riveting, sealing or replacement, with the cure times the material requires. Rushing here is paid for in flight.'],
   ['Handover with report','The repair documented with before, in-progress and after photos, for your logbook.'],
  ],
  cobT:'Coverage:', cobD:'I have worked for civil, private and government operators in all three countries, in the hangar and in the field. For trips outside my base, we agree travel and lodging beforehand.',
  aogT:'Aircraft on ground (AOG)',
  aogD:'If you have an aircraft grounded waiting on a structural repair, that is exactly the call I take first. AOG support with international mobility: I travel as soon as it is confirmed.',
  aogCta:'Call about an AOG',

  tecT:'The techniques, explained', tecN:'TO JUDGE A QUOTE',
  tecSub:'If you have never had a structure repaired, these eight words are the ones you will hear. Here they are in plain language, so you can judge a quote instead of just accepting it.',
  tecnicas:[
   ['Vacuum bagging','The lay-up is covered with a bag and vacuum is drawn while it cures. Pressure compacts the plies, pulls out air and excess resin, and leaves the right fibre-to-resin ratio. <b>Without vacuum the laminate is porous</b>: it looks the same and holds less.'],
   ['SRM, AMM and Bulletins','The <b>SRM</b> is the manufacturer’s structural repair manual: it says how big a damage can be repaired and how. The <b>AMM</b> is the maintenance manual. A <b>Service Bulletin</b> is a later instruction from the manufacturer. A repair that rests on none of the three is not an aviation repair.'],
   ['Sandwich and honeycomb','Two thin skins bonded to a honeycomb core. Stiff and very light, but if water gets in the core degrades and the part loses strength <b>with nothing showing outside</b>. It is checked by tapping: the sound changes where it is debonded.'],
   ['Doubler','A plate added to spread load around a hole or a repair — for instance where an antenna is mounted. Without a doubler, the hole edge concentrates stress and ends in a crack.'],
   ['Delamination','The plies of a composite separate from each other, usually from an impact. The surface can look untouched while it is debonded inside; that is why it is found by sound and opened until firm fibre appears.'],
   ['Dye penetrant','Non-destructive testing: a coloured liquid seeps into cracks and a developer brings them to the surface. It finds cracks in metal parts that the eye cannot see.'],
   ['Electrical bonding','Aircraft parts have to be electrically joined so a lightning strike can be conducted and static does not build up. Every time a part is removed and refitted — an antenna, a grille — that continuity <b>has to be restored</b>.'],
   ['Aviation sealing','Not silicone: specific compounds that seal joints, windows and skin transitions, resist fuel and temperature, and above all <b>keep moisture out</b>, which is where corrosion starts.'],
  ],

  trayT:'36 years inside an aircraft', trayN:'TRACK RECORD',
  traySub:'I did not start yesterday and I am not self-taught: I am an aircraft maintenance technician trained and seasoned at <b>Airbus</b>, since 1988. What I do on my own today is what I did for 36 years on a line, with its manuals and its bulletins.',
  trayectoria:[
   ['1988 — 2024','Airbus · Maintenance technician','<b>36 years on staff</b>, working structure on A320, A321, ATR 42 and ATR 72 fleets: structural inspection, sheet-metal repair, composites and modifications per <b>SRM, AMM and Service Bulletins</b>. Permanent and temporary repairs, with structural integrity and airworthiness documented.', false],
   ['2025 — today','Aeroresinas · On my own','Structural repair of <b>helicopters</b>: fibreglass, vacuum techniques, acrylics and riveted structures. For civil, private and government operators in <b>Mexico, Panama and Guatemala</b>, in the hangar or in the field — including <b>AOG support</b> with the aircraft on the ground.', true],
  ],
  capT:'What I have repaired, under that name',
  capacidades:['Radomes','Fuselage skin','Anti-ice boots','Inner cover repairs','Skin replacement','Service bulletins','Antenna installation','Door repair','Corrosion removal','Winglet modification','Dye penetrant inspection','Honeycomb sandwich panel','Doublers for antennas','Vibrating rivet replacement','Vacuum-bag structural repair','Sealing compound','Electrical bonding restoration','Insert installation and removal','Monolithic and sandwich composites','Horizontal stabiliser'],
  capP:'Twenty different jobs, from his record at Airbus. The structural and composite ones are exactly what he applies to a helicopter today: <b>same technique, different aircraft</b>.',
  pieRetrato:'<b>I am José Arturo Martínez Ponce.</b> {licencia} licence, {anios} years at {donde}, and today in your hangar.',
  quienT:'Who I am',
  quienD:'I am <b>{nombre}</b>, an aircraft maintenance technician, <b>{licencia}</b> licensed, specialised in composites, vacuum techniques and windshields.<br><br>I joined <b>Airbus in 1988</b> and spent <b>36 years</b> in structure: A320, A321, ATR 42 and ATR 72. Radomes, fuselage skin, honeycomb panels, corrosion, winglet modifications, antenna installations with their doublers, vacuum-bag repairs, sealing, electrical bonding. All per SRM, AMM and bulletins, and all documented: on a production line a repair does not exist unless it is written down.<br><br>Since <b>2025 I work on my own</b>, on helicopters: Bell, Airbus Helicopters and Robinson, for civil, private and government operators in <b>Mexico, Panama and Guatemala</b>. In the hangar when possible and in the field when needed, because a grounded aircraft costs money every day.<br><br>I am available for <b>contract projects, urgent AOG support and collaboration with MRO facilities</b>. And I answer myself: no switchboard between your aircraft and the person who will repair it.',
  credT:'What backs the work',
  credenciales:[
   ['{licencia} licence','Aircraft maintenance technician licensed by the aviation authority.'],
   ['36 years at Airbus','1988 to 2024, structure on A320, A321, ATR 42 and ATR 72.'],
   ['Repairs per manual','SRM, AMM and Service Bulletins — permanent and temporary, with airworthiness documented.'],
   ['Bell · Airbus Helicopters · Robinson','Civil, private and government operators.'],
   ['Mexico, Panama and Guatemala','In the hangar and in the field, with international mobility.'],
   ['AOG support and MRO shops','Contract projects, urgent support and collaboration with shops.'],
  ],

  floT:'The aircraft I work on', floN:'IN THE HANGAR',
  floSub:'Corporate twins, single-engine aerial-work machines, air ambulances and aircraft from operators outside Mexico. These are the type and size that come into the hangar where I repair — complete, assembled and on the line.',
  flota:[
   ['fotos/real-h145.jpg','<b>Airbus corporate twin.</b> Five blades, fenestron and a blue-over-white livery. Mexican registration.'],
   ['fotos/real-sgm.jpg','<b>Single-engine aerial-work machine.</b> Red and white livery of an institutional operator, on high skids.'],
   ['fotos/real-panama.jpg','<b>Air ambulance, HP registration.</b> HP is the Panama prefix: this is what work outside the country looks like.'],
   ['fotos/real-fenestron.jpg','<b>Fin and fenestron.</b> The tail rotor sits inside the fin. That part is pure composite, and one of the most demanding.'],
   ['fotos/real-h125.jpg','<b>H125 tail.</b> Designation and serial number painted on the fin.'],
   ['fotos/real-h145b.jpg','<b>The same twin, in profile.</b> With the aircraft this clean you cannot guess which panels were open.'],
  ],

  galT:'More from the shop', galN:'GALLERY',
  galSub:'What does not fit into a single case: the hangar, the shop built around the aircraft, vacuum bags curing, the cockpit protected and the small parts that also get repaired.',
  galeria:[
   ['fotos/hangar.jpg','<b>The hangar.</b> Work happens where the aircraft is: it does not get moved.'],
   ['fotos/trabajando.jpg','<b>In the field.</b> Sealing a window frame with the aircraft assembled.'],
   ['fotos/taller-1.jpg','<b>Aircraft opened up.</b> Doors off, interior out and the work bench beside it, extraction connected.'],
   ['fotos/taller-2.jpg','<b>On trestles.</b> Fuselage with the gear off, supported so the belly and sides can be reached.'],
   ['fotos/vacio-1.jpg','<b>Vacuum bag and lamp.</b> Bag sealed over the area and the lamp giving heat: this is how a composite cures the way the manual asks.'],
   ['fotos/vacio-2.jpg','<b>Curing under the belly.</b> The same repair from below, bag on and work under way.'],
   ['fotos/cabina.jpg','<b>Cockpit protected.</b> Seats and instruments get covered before anything is touched. Sanding dust gets everywhere.'],
   ['fotos/bahia.jpg','<b>Equipment bay.</b> Battery, avionics and ducting. To reach the skin you remove what sits on top, and put it back exactly as it was.'],
   ['fotos/circular.jpg','<b>A small repair.</b> A few centimetres beside the window: not everything is a full panel.'],
   ['fotos/louver.jpg','<b>Louvre and condenser.</b> The air-conditioning condenser sits behind the louvre, and comes out too.'],
   ['fotos/fuselaje.jpg','<b>Aircraft stripped.</b> To reach the skin you have to take off what sits on top.'],
   ['fotos/borde-ataque.jpg','<b>Leading edge open.</b> Fibre exposed, ready for new material.'],
  ],

  faqT:'What people usually ask', faqN:'FAQ',
  faq:[
   ['Can it be repaired, or does the part have to be replaced?','It depends on the size of the damage and where it is, and that is set by your aircraft manual, not by anyone’s judgement. That is why the area is opened and measured before a final price: a quote made from a photo alone is an estimate.'],
   ['How long does it take?','A small composite can be done in a day or two; a skin replacement with structure underneath takes longer, and cure times are what they are. You get the estimate with the quote, before work starts.'],
   ['Do I have to take the aircraft somewhere?','No. I go to it: your hangar, your base, or wherever it is — that is the whole point of this service, and it is why there is no shop to send it to. The exception is <b>small removed parts</b>: a cover, a fairing, a window or an acrylic panel you can hand to me, and I return it repaired and ready to fit.'],
   ['Do you work outside Mexico City?','Yes. I have worked in Mexico, Panama and Guatemala. We agree travel and lodging beforehand, and for a grounded aircraft I leave as soon as it is confirmed.'],
   ['What do you need to quote?','Photos of the area close up and from a distance, the model and registration, and the part number or manual page if you have it. That is enough for a first answer.'],
   ['What do I get at the end?','The repaired aircraft and a report with before, in-progress and after photos, for your logbook.'],
   ['Do you work with MRO shops?','Yes, and it is part of what I offer: collaboration with shops on structure and composite work, by contract or by project.'],
   ['What if the damage exceeds the manual?','I tell you, and it is not repaired: it is replaced. Preferring a patch the manual does not cover is exactly what is not done here.'],
  ],

  conT:'Tell me what happened to your aircraft',
  conSub:'One photo and two lines and I tell you whether it can be fixed and what it costs. I answer, not a switchboard.',
  visorAyuda:'CLICK THE PHOTO FOR FULL SIZE · ← → TO MOVE',
  kWa:'WHATSAPP', kMail:'EMAIL', kIn:'LINKEDIN', kEmp:'COMPANY', kBase:'BASED IN', kLic:'LICENCE',
  formT:'Send him the case', fNombre:'NAME', fAeronave:'AIRCRAFT', fQue:'WHAT HAPPENED',
  phNombre:'Your name', phAeronave:'Model and registration — e.g. Bell 407, XA-XXX', phQue:'Two lines: where the damage is and since when',
  formNota:'WhatsApp opens with the message already written. You send me the photos right there.',
  formBtn:'Send over WhatsApp',
  waSaludo:'Hello, I saw the Aeroresinas page.',
  waNombre:'I am', waAeronave:'Aircraft', waQue:'What happened',
  waAog:'Hello, I have an aircraft on ground (AOG) and need a structural repair.',
 }
};
